### ISSUE TITLE
Rust_Tools.nvim and Rust-analyzer

### ISSUE THREAD

**Issue by ulrikmonrad** [abzcoding/lvim#1]
Hi abzcoding,

Have you figured out to get rust-analyzer and rust_tools functioning correctly in lunarvim?

I've gone sideways trying to figure out how to get the [shift-k] hover definition of functions and inlay hints working from these two addons to facilitate learning Rust, but no matter what i've tried it's not getting anywhere. I tried pulling your lvim config to see if it worked in that, but alas no dice.

**Comment by abzcoding** [comment]
this is what i see using my config
<img width="1677" alt="Screen Shot 2021-08-28 at 7 09 21 PM" src="https://user-images.githubusercontent.com/10992695/131221614-71381330-92d7-4450-bc32-18840c34b6a3.png">

**Comment by abzcoding** [comment]
i'm not sure how to help i can help you further, cause it is fairly dependent on your environment
on the fact that have you installed language server or not and etc
but hop on discord, i might be able to better help you there

**Comment by ulrikmonrad** [comment]
Yeah, i'm not getting the pop-up window at all. Strange.

**Comment by abzcoding** [comment]
have you tried a different terminal or sth?
i'm using alacritty.
