### ISSUE TITLE
How do I find these lovely icons?🙏🏻🙏🏻🙏🏻

### ISSUE THREAD

**Issue by Leiyi548** [abzcoding/lvim#10]
![image](https://user-images.githubusercontent.com/76139422/141237255-f1649590-f5cc-4cdf-8a42-4b01f486c938.png)
This is very cute. I want a similar icon. I hope I can get your help

**Comment by abzcoding** [comment]
Usually, I would search for other people's configurations and pick and choose what I want out of them ( including the cute icons ), so not sure if there is a single repository for all these icons or not.

**Comment by abzcoding** [comment]
that said, here are some sample

https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua

https://github.com/davidosomething/vim-devicons/blob/master/plugin/webdevicons.vim

**Comment by Leiyi548** [comment]
@abzcoding  Thank you, but it seems that there are only some file type icons

**Comment by abzcoding** [comment]
> @abzcoding Thank you, but it seems that there are only some file type icons

yeah, I usually find them in random places 😅

**Comment by abzcoding** [comment]
@Leiyi548 some more icons in case you need them
https://github.com/lambdalisue/glyph-palette.vim/blob/master/autoload/glyph_palette/defaults.vim#L7

**Comment by abzcoding** [comment]
also more icons :)

https://www.nerdfonts.com/cheat-sheet
