### ISSUE TITLE
does copilot.lua works for you?

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#100]
i tried the lua version with cmp of copilot, but i struggle to get it working .. i got the message Copilot is not running. when i enter :Copilot auth (i opened a py file)
the normal tpope version works fine

**Comment by luxus** [comment]
```
diff --git a/lua/user/plugins.lua b/lua/user/plugins.lua
index f569399..0c7ebde 100644
--- a/lua/user/plugins.lua
+++ b/lua/user/plugins.lua
@@ -387,17 +387,25 @@ M.config = function()
     },
     {
       "zbirenbaum/copilot.lua",
-      after = "nvim-cmp",
-      requires = { "zbirenbaum/copilot-cmp" },
+      event = { "VimEnter" },
       config = function()
-        local cmp_source = { name = "copilot", group_index = 2 }
-        table.insert(lvim.builtin.cmp.sources, cmp_source)
         vim.defer_fn(function()
-          require("copilot").setup()
+          require("copilot").setup {
+            plugin_manager_path = os.getenv "LUNARVIM_RUNTIME_DIR" .. "/site/pack/packer",
+          }
         end, 100)
       end,
       disable = not lvim.builtin.sell_your_soul_to_devil.prada,
     },
+
+    {
+      "zbirenbaum/copilot-cmp",
+      after = { "copilot.lua" },
+      config = function()
+        require("copilot_cmp").setup()
+      end,
+      disable = not lvim.builtin.sell_your_soul_to_devil.prada,
+    },
     {
       "ThePrimeagen/harpoon",
       requires = {

```
something like this... i just copied some stuff around :D

**Comment by rebuilt** [comment]
I'd check the lsp logs.  I initially set up zbirenbaum/copilot-cmp and it worked for a while but at some point it stopped working.  I switched back to tpope's version and it threw more explicit error messages about my version of node.  At the time I think it only worked with version 12 of node.   So I downgraded node and got it working.  

I probably didn't need to switch plugins, just downgrade my node version.

**Comment by alechp** [comment]
### copilot.vim 
- was working earlier, did fresh lvim and bloated-lvim install 
- confirmed authenticated
- confirmed have active copilot for the authenticated account

<details><summary>screenshots</summary>
<img width="374" alt="Screen Shot 2022-11-24 at 7 23 12 PM" src="https://user-images.githubusercontent.com/3058939/203894097-ac02d457-2012-412a-b3ce-2921c96e5af0.png">
<img width="502" alt="Screen Shot 2022-11-24 at 7 22 41 PM" src="https://user-images.githubusercontent.com/3058939/203894101-48d43374-0ff9-4b72-872a-1e78e0504954.png">
<img width="404" alt="Screen Shot 2022-11-24 at 7 16 31 PM" src="https://user-images.githubusercontent.com/3058939/203894102-0c5b58bb-1ad7-4a4e-8374-b3beb5fb9dcd.png">
<img width="811" alt="Screen Shot 2022-11-24 at 7 24 56 PM" src="https://user-images.githubusercontent.com/3058939/203894236-efcf08c3-b321-43b3-9ec0-8134c6cdd49e.png">
<img width="725" alt="Screen Shot 2022-11-24 at 7 25 19 PM" src="https://user-images.githubusercontent.com/3058939/203894275-ce09c535-170a-4191-bdba-d1ce430850fe.png">
</details>

Going to continue debugging, just wanted to log what I'm seeing so far

**Comment by luxus** [comment]
copilot.vim works fine, cannot reproduce 

after some modifications I got even cmp working.

**Comment by luxus** [comment]
cmp variant is not stable or working correctly for me.
does anyone else have luck with it?

**Comment by luxus** [comment]
*shrug*
