### ISSUE TITLE
LS for rust is not startup automatically.

### ISSUE THREAD

**Issue by l1nxy** [abzcoding/lvim#101]
OS: Arch LInux.
Nvim version: NVIM v0.9.0-dev
I just follow the document and install this config, and open rust-tools plugin, but the rust-analyzer is not start up automatically, but it can start if i input `LspStart`.maybe there are some mistake in file type detection.

**Comment by abzcoding** [comment]
is your rust project git managed?

**Comment by l1nxy** [comment]
> is your rust project git managed?

Yes.

**Comment by l1nxy** [comment]
> can you directly open a rust file? ( instead of using telescope) do you get any errors?
> 
> ```shell
> lvim src/main.rs
> ```

I tried too, it is same result. But i found TS is broken, and find https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/316 is here, i not sure is this TS issue make LS broken.

**Comment by abzcoding** [comment]
yep that is the issue, i just did a commit, please get that and run `:PackerInstall`
