### ISSUE TITLE
TokyoNight

### ISSUE THREAD

**Issue by jacula** [abzcoding/lvim#102]
After a clean install of LunarVim and configuring abzcoding (considering all dependencies) I get this worning:

``
15:53:21 [WARN ] lvim: "Invalid configuration: /home/xxxx/.config/lvim/lua/user/theme.lua:76: attempt to index field 'tokyonight' (a nil value)" file="init.lua", line=129
``

This makes it impossible to install the various modules foreseen by the configuration

**Comment by abzcoding** [comment]
a. please don't use this repo as is ( as mentioned in the docs
<img width="681" alt="Screenshot 2022-11-16 at 7 19 22 PM" src="https://user-images.githubusercontent.com/10992695/202227800-df7de438-9f9c-4272-bb84-4363eea36b0f.png">

b. I'm using the `master` branch of lunarvim, not a release

**Comment by jacula** [comment]
a. I tried with your wezterm configuration. I am not using tmux. I don't know your Zsh configuration. The my Zsh configuration is ok for lunarvim  and neovide. But, the problem rises also with bash or tcsh.
b. I'm using the ``master`` branch

**Comment by abzcoding** [comment]
That was not the point, mate 😅 , the point was( just pick and choose from my config, don't use it as a whole)

anyway
please do a `:PackerSync`
also is the output of this command?
```shell
git -C ~/.local/share/lunarvim/lvim branch -v
```

**Comment by jacula** [comment]
I got well your point, but just wanted to provide more information. However, updates and sync have been done and proceed regardless of your repository configuration. In fact, PackerSync and PackerUpdate only consider the basic 42 packs provided by LunarVim. Since I've been using your setup for a while now with no issues I'm guessing this is a bug.

For example, I have another installation of lunarvim (always on ubuntu with the same settings) which is perfectly functional:

``commit cad528b56d703e62fcc6f4c16084d60271cb73bb``
``Author: abzcoding <abzcoding@gmail.com>``
``Date:   Wed Oct 19 18:30:37 2022 +0330````

``    highlight cleanup``


About git -C ~/.local/share/lunarvim/lvim branch -v:

``* rolling 7d57046 fix(breadcrumbs): use hlgroup from web devicons in breadcrumbs (#3342)``

**Comment by abzcoding** [comment]
well it seems like you are in fact not on the `master` branch

you are on the `rolling` branch

please uninstall, and reinstall using these commands:
```shell
# uninstall
bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh

# install master branch
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
```

**Comment by jacula** [comment]
Yes, I'm sorry. Now, it's ok. The problem doesn't exist. 

I was thinking my way and in my head I meant ``master`` as referring to your configuration directory. I got distracted and wasted your time. Excuse me.

Thank you very much for your kind replies.

**Comment by abzcoding** [comment]
> Yes, I'm sorry. Now, it's ok. The problem doesn't exist.
> 
> I was thinking my way and in my head I meant `master` as referring to your configuration directory. I got distracted and wasted your time. Excuse me.
> 
> Thank you very much for your kind replies.

no worries mate, we've all been there 😅 , have a good one
