### ISSUE TITLE
inline hints causes rust_tools to throw on every keypress

### ISSUE THREAD

**Issue by alechp** [abzcoding/lvim#105]
Example of issue:
> <img width="2032" alt="Screen Shot 2022-12-30 at 12 33 40 PM" src="https://user-images.githubusercontent.com/3058939/210109906-cd33d3ae-0704-4a44-9394-a3b1c79f33a2.png">

Upstream issue fix:
> https://github.com/simrat39/rust-tools.nvim/issues/300

Possibly result of adding inline_hints here:
> https://github.com/alechp/bloated-lvim/commit/6dac199a6a2de487eed1f408f1c156ef271e934f 

Will submit PR for this soon:
> <img width="2032" alt="Screen Shot 2022-12-30 at 12 35 26 PM" src="https://user-images.githubusercontent.com/3058939/210109964-bc1d84b1-ba15-4083-8337-1832305842c1.png">

**Comment by abzcoding** [comment]
fixed via #106
