### ISSUE TITLE
Error config bigfile

### ISSUE THREAD

**Issue by fabiano-amaral** [abzcoding/lvim#107]
https://github.com/abzcoding/lvim/blob/420911a77452ceb3d4c2a27726d83192f2cb3f3c/config.lua#L78

I think that should be 
```lua
lvim.builtin.bigfile = { active = true }
```

**Comment by abzcoding** [comment]
it is already defined here

https://github.com/LunarVim/LunarVim/blob/9bc82e4e684aa548eb0765734ec4e83f16c78b4c/lua/lvim/config/init.lua#L38


we don't need to redefine the entire thing

**Comment by fabiano-amaral** [comment]
@abzcoding Hmmm I was getting an error while using neovim 8.2 and a fresh lunarvim installation, so after I did the change worked for me, but can be some particularity of my env
