### ISSUE TITLE
config.lua not working properly for filetree_provider

### ISSUE THREAD

**Issue by ksajan** [abzcoding/lvim#109]
I am not sure why this is happening. I tried looking around in the code to see why this is happening in the config.lua its written as 
`lvim.builtin.tree_provider = "nvimtree"`.  Can you help me understand this problem? 

![image](https://user-images.githubusercontent.com/31013555/210444289-2b3833ce-a0d1-49d6-85a3-8a9ae81c4863.png)

**Comment by abzcoding** [comment]
have you tried closing and reopening lunarvim and running `:PackerInstall` afterward?

**Comment by ksajan** [comment]
I think that was the issue as it was overriding using the custom_user file. Sorry for the stupid question and Thank you for helping.

**Comment by abzcoding** [comment]
> I think that was the issue as it was overriding using the custom_user file. Sorry for the stupid question and Thank you for helping.

No worries mate
