### ISSUE TITLE
Does lua-dev still provide type signatures for you?

### ISSUE THREAD

**Issue by chase** [abzcoding/lvim#11]
Doesn't seem to be working for me recently

**Comment by abzcoding** [comment]
sadly no, it seems like it is not compatible with the recent neovim versions
<img width="969" alt="Screen Shot 2021-11-11 at 12 54 55 PM" src="https://user-images.githubusercontent.com/10992695/141272802-c746da5c-79e6-40be-a113-50de164611b5.png">
<img width="424" alt="Screen Shot 2021-11-11 at 12 55 39 PM" src="https://user-images.githubusercontent.com/10992695/141272874-e5350ef7-4bb9-4236-a8d2-a4f471088a0f.png">

**Comment by abzcoding** [comment]
weirdly enough, copilot works 😅 
<img width="669" alt="Screen Shot 2021-11-11 at 12 56 46 PM" src="https://user-images.githubusercontent.com/10992695/141273138-10e3c61a-871a-47e0-97be-29843d761013.png">
<img width="432" alt="Screen Shot 2021-11-11 at 12 57 28 PM" src="https://user-images.githubusercontent.com/10992695/141273185-b1fcc6b9-cbe1-4f36-ae79-7f5c32b70c73.png">

**Comment by chase** [comment]
> weirdly enough, copilot works sweat_smile <img alt="Screen Shot 2021-11-11 at 12 56 46 PM" width="669" src="https://user-images.githubusercontent.com/10992695/141273138-10e3c61a-871a-47e0-97be-29843d761013.png"> <img alt="Screen Shot 2021-11-11 at 12 57 28 PM" width="432" src="https://user-images.githubusercontent.com/10992695/141273185-b1fcc6b9-cbe1-4f36-ae79-7f5c32b70c73.png">

I refuse to accept that :joy:

I wonder if it's because the file locations changed around for the nightly builds, I guess I'll look into that.

**Comment by abzcoding** [comment]
> I wonder if it's because the file locations changed around for the nightly builds, I guess I'll look into that.

yeah it should be related

**Comment by chase** [comment]
Even after regenerating the types it didn't work so I started looking into it more deeply and checked the debug long.
Even after running lspconfig's setup with the enhanced config, it seems like even with the override the default config is being passed:
```
[18:10:28.495][debug][#0:script/provider/provider.lua:43]: loaded config dump:	{
    Lua = {
        diagnostics = {
            globals = {
                [1] = "vim",
                [2] = "lvim",
            },
        },
        telemetry = {
            enable = false,
        },
        workspace = {
            library = {
                ["/home/chase/.local/nvim/usr/share/nvim/runtime/lua"] = true,
                ["/home/chase/.local/nvim/usr/share/nvim/runtime/lua/vim/lsp"] = true,
                ["/home/chase/.local/share/lunarvim/lvim/lua"] = true,
            },
            maxPreload = 100000,
            preloadFileSize = 10000,
        },
    },
}
```

**Comment by abzcoding** [comment]
that is weird 🤔

**Comment by chase** [comment]
Hard to tell if this a sumneko_lua bug or an lspconfig bug, but the config passed to lspconfig.setup is correct:
![image](https://user-images.githubusercontent.com/5411/141283319-b7e285ca-392e-47e3-889b-1ede88fb651d.png)

**Comment by abzcoding** [comment]
😢

**Comment by chase** [comment]
Got a fix for you that seems to work.

Drop this part of your config:
https://github.com/chase/lvim/commit/7c4f5c1d6d6693e8d677cbe8d8eb082ca7f09a43#diff-437dcbdcefbb257379ec6d95c6877f5f4feb823b3c5d920b643f9aeebcad7db0L303-L308

Move `lua/user/providers` to `lua/lvim/lsp/providers`:
https://github.com/chase/lvim/commit/7c4f5c1d6d6693e8d677cbe8d8eb082ca7f09a43#diff-072b5a568c83434dda5a33ca67ecdcb46358ba94308236464a9dc8b1578bbff7

**Comment by abzcoding** [comment]
tyvm! 
Fixed via https://github.com/abzcoding/lvim/commit/8331fd9774ad2502263df61ba97ae9472c689d4f
