### ISSUE TITLE
lua debug error!

### ISSUE THREAD

**Issue by jeryaiwei** [abzcoding/lvim#110]
dap.adpters.nlua is undefined.

**Comment by abzcoding** [comment]
can you try adding this to https://github.com/abzcoding/lvim/blob/52875bad29b13e2f4a356fbccdaa04c2c66dfbcd/lua/user/dap.lua#L37
```lua
dap.adapters.nlua = function(callback, config)
  callback({ type = 'server', host = config.host or "127.0.0.1", port = config.port or 8086 })
end
```

and see if that fixes your issue?

**Comment by luxus** [comment]
its crazy that you even knew what he meant :D

**Comment by abzcoding** [comment]
> its crazy that you even knew what he meant :D

I'm not even sure that's what he meant 😅

**Comment by Uzaaft** [comment]
Abz is built different.
