### ISSUE TITLE
Unable to select or identify these autocompletion suggetions

### ISSUE THREAD

**Issue by ksajan** [abzcoding/lvim#112]
I am unable to identify where this autocompletion is coming from. I cannot even select them either through tab/enter/shift-tab/enter.  This type of suggestion comes when I have already chosen an autocompletion from the buffer or something then after that they are auto-suggestions and it even makes it harder to navigate after that.  Please see the screenshots attached below. 

The second screenshot with the suggestion with [A]/[B] is the one I am talking about. Thanks for the help. 
<img width="1800" alt="Screenshot 2023-01-11 at 3 33 11 PM" src="https://user-images.githubusercontent.com/31013555/211777246-a911ee1a-c27b-4f59-995b-00c56528685c.png">
<img width="1800" alt="Screenshot 2023-01-11 at 3 33 19 PM" src="https://user-images.githubusercontent.com/31013555/211777264-1de298dd-d903-4610-a730-e96c113c0d04.png">

**Comment by Uzaaft** [comment]
The autocompletion(false: keyword) is from the LSP.
Regarding the issue with tab etc, what terminal are you using?

**Comment by ksajan** [comment]
iterm
In the second screenshot suggestion(task_runner [A]) is what I asking about. Cause I am unable to toggle it off.

**Comment by Uzaaft** [comment]
Have you tried using the escape button?

**Comment by ksajan** [comment]
Yes, That works as it's going to normal mode. So all suggestions get toggled off automatically. Do you know where does this specifically comes from ?

**Comment by Uzaaft** [comment]
I have no idea, I have never had that issue myself.

**Comment by ksajan** [comment]
okay, no problem. I will try checking every plugin.  Thanks for the help!

**Comment by abzcoding** [comment]
That is very weird. Do you have your configuration somewhere so I can debug it locally?

**Comment by ksajan** [comment]
I was using your config with some changes. I am not sure what was the problem when I updated to this new it went off. I had the same configuration on my other machine with arch Linux on it. It didn't have that issue.
