### ISSUE TITLE
Missing highlights after moving to lazy.nvim

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#113]
Hello, I am using your config as a base for mine, so it is likely its a problem I introduced. I am asking here because I am completely lost and I tried more or less everything I could think of. Feel free to just close and ignore this issue if you need.

Switching to lazy.nvim, following the PR you recently merged made some of the highlights disappear for me. I have a `user.theme` that is practically identical to yours ([here](https://github.com/crisidev/dotfiles/blob/4db6b81c082b1ecae97ba5aa0deace0c7c918a28/home/.config/lvim/lua/user/theme.lua)) and I call `require("user.theme").telescope_theme()` in an autocmd ([here](https://github.com/crisidev/dotfiles/blob/main/home/.config/lvim/lua/user/autocmd.lua#L7)).

After migrating to lazy.nvim, using the tokyonight theme, `bufferline`, `fidget-spinner` and lualine are missing some hightlights: 

![2023-01-11_15-55](https://user-images.githubusercontent.com/1781140/211853618-3040d735-7a78-42a3-8a2e-915491be39ef.png)

Any clue of what could I check to solve this?

Thanks for the amazing work you are doing here!

**Comment by crisidev** [comment]
I debugged this a little bit further and it seems like `require("user.theme").telescope_theme()` does not get applied even if it is part of the autocommands. If I call the function manually while fidget spinner is running, the hightlight gets applied properly.

The while part on `bufferline` is still white.

**Comment by crisidev** [comment]
Another new, changing the autocmd from `Colorscheme` to `VimEnter` fixes the fidget spinner highlight.

Regarding the `bufferline` issue, I think my call to `require("user.theme").tokyonight()` is being sort of ignore as I believe the colour should come from `NormalNC`...

**Comment by crisidev** [comment]
I have done it already, but I had to change the event from "ColorScheme" to "VimEnter"..

**Comment by abzcoding** [comment]
You can change the details of your lualine by editing https://github.com/abzcoding/lvim/blob/79ce35a4d9b9c10b8d2ebeb627b1b3c9cb8eb3a5/lua/lualine/themes/tokyonight.lua#L5

and the bufferline color only changes if
https://github.com/abzcoding/lvim/blob/79ce35a4d9b9c10b8d2ebeb627b1b3c9cb8eb3a5/lua/user/bufferline.lua#L9-L16

**Comment by crisidev** [comment]
Found and resolved all the issues. Turns out `slant` for bufferline does not work well with transparent_window. Thanks for the help, resolving this.
