### ISSUE TITLE
smart_quit() is gone from upstream LunarVim.

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#115]
FYI this is not available anymore in LunarVim.

https://github.com/abzcoding/lvim/blob/e25cbd4b9b8e733d8c637303b7de519b3480335b/lua/user/keybindings.lua#L363

**Comment by abzcoding** [comment]
thanks for the headsup

**Comment by crisidev** [comment]
I did not post a PR because I did not know what you wanted to do :) I personally really liked the smart_quit() functionality, so I added it to my config: https://github.com/crisidev/dotfiles/blob/main/home/.config/lvim/lua/user/builtin.lua#L110

**Comment by abzcoding** [comment]
> I did not post a PR because I did not know what you wanted to do :) I personally really liked the smart_quit() functionality, so I added it to my config: https://github.com/crisidev/dotfiles/blob/main/home/.config/lvim/lua/user/builtin.lua#L110

thanks, but I don't use that functionality at all, so ...
