### ISSUE TITLE
How to deactivate or customize spellcheck

### ISSUE THREAD

**Issue by ziriuz84** [abzcoding/lvim#119]
I don't know how, but I activated spell checking. The problem is that I write in italian and all not english words are signed as wrong. What are you using for spell checking and how can I add another language dictionary? Or how can I deactivate it?

**Comment by ziriuz84** [comment]
![immagine](https://user-images.githubusercontent.com/464498/213263869-9af63471-aabb-4ce8-8a4c-d708a8392333.png)

This is the effect writing an Italian Markdown file

**Comment by abzcoding** [comment]
first run this to make sure what is the `spell` status for you

```vim
:verbose set spell?
```

if that outputs `nospell`

then try disabling `vale` by commenting these lines
https://github.com/abzcoding/lvim/blob/31b1620ce6f40ccfe4343e74e7c4a29dd50cb137/lua/user/null_ls/init.lua#L86-L89

**Comment by abzcoding** [comment]
closed due to inactivity
