### ISSUE TITLE
Lazyloading tabnine

### ISSUE THREAD

**Issue by Uzaaft** [abzcoding/lvim#12]
Hi, 

Have you figured out how to lazyload tabnine so that it does not add about 700 ms(on my machine) to the startup time?

I tried, but unsuccessfully.

**Comment by abzcoding** [comment]
wow, it takes literally nothing on my machine to load 😢 
can you try my latest commit? let me know if it helps
https://github.com/abzcoding/lvim/commit/7bc5e89966130d07563110bde05c88752761683e

**Comment by Uzaaft** [comment]
You freaking magician! Much faster

**Comment by Uzaaft** [comment]
Btw, what`s your tmux config like? it looks amazing...

**Comment by abzcoding** [comment]
> Btw, what`s your tmux config like? it looks amazing...

oh i have a shit ton of stuff in it, 🤞 i'll eventually push those to a public repo as well

**Comment by Uzaaft** [comment]
xD Bummer. I want it now 😔

**Comment by Uzaaft** [comment]
@abzcoding Do you know how I can lazy load a plugin, but load it in at startup, after opening up a file or the dash? Didn't know how to reach you, so I am asking you here xD

**Comment by abzcoding** [comment]
you can usually add 
```lua
      event = "BufRead",
```
