### ISSUE TITLE
jdtls is not configured correctly

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#120]
jdtls has the bundles for debug and test not configured correctly after switching to Mason. I have fixed it in my dotfiles https://github.com/crisidev/dotfiles.

Currently the one in this repo errors out with something like "no such bundle", causing the default jdtls to start and the one configured to attach to start as well without attaching, causing all sort of issues.

I'll send a PR to fix this tomorrow PST time. Now `java-debug` and `java-test` can be installed directly using Mason.

**Comment by abzcoding** [comment]
a PR would be much appreciated <3
