### ISSUE TITLE
we miss you :D

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#122]
@abzcoding are you still on discord?
can you add me? luxus#1911 
@Uzaaft and I miss you <3

**Comment by Uzaaft** [comment]
Don't forget about me! uzaaft#838

**Comment by abzcoding** [comment]
Guys, I still use the same old discord. I just haven't opened it in a long while 😅 
I will try to activate it again.

p.s: miss you guys as well

**Comment by abzcoding** [comment]
Guys, I still use the same old discord. I just haven't opened it in a long while 😅 
I will try to activate it again.

p.s: miss you guys as well

**Comment by luxus** [comment]
![Jan-30-2023 13-27-34](https://user-images.githubusercontent.com/7449/215476895-d4681255-2d7e-4de3-950c-a32c0881c882.gif)

we don't have you in discord, you have to add us :D 

we found a new home btw :D

**Comment by abzcoding** [comment]
> Don't forget about me! uzaaft#838

shouldn't there be 4 numbers in there?
