### ISSUE TITLE
Lsp diagnostics disappear after edition 

### ISSUE THREAD

**Issue by williamgoulois** [abzcoding/lvim#127]
Hi @abzcoding,

Since a few weeks I have an issue with LSP. The diagnostics disappear and I must restart the lsp server or delete+undo line to show them again. It would be amazing if you could fix this 🙂
This is usually how it happens : 
 - I write an incorrect line and tsserver correctly show me errors
 - I edit the line by deleting with `x`, `d`, `c` or entering insert mode
 - the diagnostics disappear even if i'm back into normal mode
 
I tested with your latest config, latest initial Lunarvim config and could only reproduce this with your config.

Video to show this in action : 

`basic lunarvim config` => Working correctly

https://user-images.githubusercontent.com/37271970/227794991-ed595398-7f13-4e7d-a87d-80ab95deebba.mov

`basic abzcoding config` => Not working correctly

https://user-images.githubusercontent.com/37271970/227795127-0ccf7d1c-3ca3-4efb-9b0b-4b5de0481cbb.mov

**Comment by abzcoding** [comment]
@williamgoulois can you check if commenting these lines does anything?
https://github.com/abzcoding/lvim/blob/e0ef507a84ce6f203d980cc4d9b6509546068bc8/lua/user/builtin.lua#L283-L292

**Comment by williamgoulois** [comment]
@abzcoding Thank you for your quick response !
I tested with these lines commented and the problem is still there 🙁

**Comment by williamgoulois** [comment]
I tried to disable all user plugins by commenting these lines and the problem is fixed, so it is coming from one of our custom plugins or configs
https://github.com/abzcoding/lvim/blob/e0ef507a84ce6f203d980cc4d9b6509546068bc8/config.lua#L146-L148

**Comment by williamgoulois** [comment]
@abzcoding UPDATE: I did a little bisect when i disabled each plugin one by one and I think found the culprit : `lsp_signature.nvim`
By disabling the bug is gone. Will look into it's configuration to try to fix it

**Comment by williamgoulois** [comment]
I managed to fix it partially with https://github.com/ray-x/lsp_signature.nvim/issues/260
If I add `cursorhold_update = false` and use `floating_window` instead of `hint` it works. But cannot managed to get it to work with `hint` 🙁

**Comment by abzcoding** [comment]
> Well it is not consistent if i add a new argument to the function it clear diagnostics... So for the moment I will disable this plugin

thanks for digging into this 👍

**Comment by ksajan** [comment]
I am getting this error `method textDocument/definition is not supported by any of the servers registered for the current buffer` Is it because of this? This comes when I try to type space+gd, which refers to a function or user hover method. It's not working in any language now. I tried multiple times to clean and reinstall but I got the same result.

**Comment by abzcoding** [comment]
> I am getting this error `method textDocument/definition is not supported by any of the servers registered for the current buffer` Is it because of this? This comes when I try to type space+gd, which refers to a function or user hover method. It's not working in any language now. I tried multiple times to clean and reinstall but I got the same result.

can you check if creating a file in `~/.config/lvim/after/ftplugin/` like for example `~/.config/lvim/after/ftplugin/lua.lua`
and filling it with

```lua
local lsp_active = true
local buf_clients = vim.lsp.get_active_clients { bufnr = 0 }
if #buf_clients == 0 then
  lsp_active = false
end
-- add client
for _, client in pairs(buf_clients) do
  if client.name == "lua_ls" then
    lsp_active = true
  end
end
if not lsp_active then
  vim.cmd [[LspStart lua_ls]]
end
```
fixes the issue or not?

**Comment by ksajan** [comment]
> > I am getting this error `method textDocument/definition is not supported by any of the servers registered for the current buffer` Is it because of this? This comes when I try to type space+gd, which refers to a function or user hover method. It's not working in any language now. I tried multiple times to clean and reinstall but I got the same result.
> 
> can you check if creating a file in `~/.config/lvim/after/ftplugin/` like for example `~/.config/lvim/after/ftplugin/lua.lua` and filling it with
> 
> ```lua
> local lsp_active = true
> local buf_clients = vim.lsp.get_active_clients { bufnr = 0 }
> if #buf_clients == 0 then
>   lsp_active = false
> end
> -- add client
> for _, client in pairs(buf_clients) do
>   if client.name == "lua_ls" then
>     lsp_active = true
>   end
> end
> if not lsp_active then
>   vim.cmd [[LspStart lua_ls]]
> end
> ```
> 
> fixes the issue or not?

Nope, It doesn't fix the issue.

**Comment by abzcoding** [comment]
> Nope, It doesn't fix the issue. I am on nvim version 9.1. And while searching I got to know about null-ls being archived. Is it because of that or its something else.

not sure tbh

**Comment by ksajan** [comment]
Its fixed. `https://github.com/LunarVim/LunarVim/issues/4355#issuecomment-1703802360`
