### ISSUE TITLE
Question around hover with jdtls

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#129]
I took a lot of inspiration from your repo and I am facing an issue with jdtls that I am unable to debug.

If you have the time, would you mind to open a java file and try to get the hover of any class using `K` and tell me if it works for you?

For me it tries relentlessly to open a man page with the name of the class 😂

**Comment by crisidev** [comment]
Any other LSP works as expected..

**Comment by abzcoding** [comment]
This code is responsible for `K`. You can change it as you wish:
https://github.com/abzcoding/lvim/blob/be2a4ad3b60ba9f1cbd1d3e3a78c880c1f72d0ec/lua/user/builtin.lua#L743-L761

Mine seems to be working fine:
<img width="498" alt="Screenshot 2023-04-22 at 18 00 01" src="https://user-images.githubusercontent.com/10992695/233790776-57e1089e-2ab4-4caf-bc0b-c3b7bbb6a05e.png">

**Comment by crisidev** [comment]
Yeah I have a very similar function, but it is not called in Java. It is in any other language.. I'll dig more into this. Thanks for the confirmation that this works for you.
