### ISSUE TITLE
LSP clangd is unavailable.

### ISSUE THREAD

**Issue by huguanghui** [abzcoding/lvim#130]

**Comment by huguanghui** [comment]
"p00f/clangd_extensions.nvim",

**Comment by huguanghui** [comment]
LSP currently has a BUG, opening a .c file will not start the LSP service, only opening the second file will start

**Comment by abzcoding** [comment]
Fixed via https://github.com/abzcoding/lvim/commit/432a2a77b5cce9a38b98a98c0aefb862c06ed89e

**Comment by ksajan** [comment]
I having weird issues with this update. Am  I missing something here? 
```
ensions.cmp_scores' not found:\n\tno field package.preload['clangd_extensions.cmp_scores']\n\tno file './clangd_ext
ensions/cmp_scores.lua'\n\tno file '/usr/share/luajit-2.1.0-beta3/clangd_extensions/cmp_scores.lua'\n\tno file '/us
r/local/share/lua/5.1/clangd_extensions/cmp_scores.lua'\n\tno file '/usr/local/share/lua/5.1/clangd_extensions/cmp_
scores/init.lua'\n\tno file '/usr/share/lua/5.1/clangd_extensions/cmp_scores.lua'\n\tno file '/usr/share/lua/5.1/cl
angd_extensions/cmp_scores/init.lua'\n\tno file './clangd_extensions/cmp_scores.so'\n\tno file '/usr/local/lib/lua/
5.1/clangd_extensions/cmp_scores.so'\n\tno file '/usr/lib/lua/5.1/clangd_extensions/cmp_scores.so'\n\tno file '/usr
/local/lib/lua/5.1/loadall.so'\n\tno file './clangd_extensions.so'\n\tno file '/usr/local/lib/lua/5.1/clangd_extens
ions.so'\n\tno file '/usr/lib/lua/5.1/clangd_extensions.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'" file="[
C]", line=-1
```

**Comment by abzcoding** [comment]
> I having weird issues with this update. Am I missing something here?
> 
> ```
> ensions.cmp_scores' not found:\n\tno field package.preload['clangd_extensions.cmp_scores']\n\tno file './clangd_ext
> ensions/cmp_scores.lua'\n\tno file '/usr/share/luajit-2.1.0-beta3/clangd_extensions/cmp_scores.lua'\n\tno file '/us
> r/local/share/lua/5.1/clangd_extensions/cmp_scores.lua'\n\tno file '/usr/local/share/lua/5.1/clangd_extensions/cmp_
> scores/init.lua'\n\tno file '/usr/share/lua/5.1/clangd_extensions/cmp_scores.lua'\n\tno file '/usr/share/lua/5.1/cl
> angd_extensions/cmp_scores/init.lua'\n\tno file './clangd_extensions/cmp_scores.so'\n\tno file '/usr/local/lib/lua/
> 5.1/clangd_extensions/cmp_scores.so'\n\tno file '/usr/lib/lua/5.1/clangd_extensions/cmp_scores.so'\n\tno file '/usr
> /local/lib/lua/5.1/loadall.so'\n\tno file './clangd_extensions.so'\n\tno file '/usr/local/lib/lua/5.1/clangd_extens
> ions.so'\n\tno file '/usr/lib/lua/5.1/clangd_extensions.so'\n\tno file '/usr/local/lib/lua/5.1/loadall.so'" file="[
> C]", line=-1
> ```

run `lazy sync` to make sure you have everything you need

`cmp_scores` is available here https://github.com/p00f/clangd_extensions.nvim/blob/main/lua/clangd_extensions/cmp_scores.lua
