### ISSUE TITLE
Edition mode after opening a new buffer

### ISSUE THREAD

**Issue by williamgoulois** [abzcoding/lvim#132]
I just updated to latest neovim + lunarvim + your config and I have a problem : 

When I open a new buffer, I often hold `j` to scroll down the buffer as soon as it is opened. It writes `jjjjjjjjjjj` and I am in `EDIT MODE` 🤔

I don't know why I am in EDIT MODE instead of NORMAL MODE

https://github.com/abzcoding/lvim/assets/37271970/ea9cd310-9671-45e1-9865-e94645c76e57

**Comment by abzcoding** [comment]
sadly I can't reproduce the issue,
can you check if `j` is mapped to anything or not
also, does it only happen when you open a file from history (using `r`), or does the same happens when you use explore (`f`) and new file (`e`) as well?

**Comment by abzcoding** [comment]
i cannot reproduce that either, what might cause it 🤔

**Comment by soerenmartius** [comment]
After pulling the latest changes I am running into the issue

**Comment by abzcoding** [comment]
Can you guys check if these commands help or not?
```bash
cd ~/.local/share/lunarvim/lvim
make generate_new_lockfile
# open lvim and run `:Lazy sync`
lvim
```

**Comment by williamgoulois** [comment]
@abzcoding Hi 👋
I tried to generate new lockfile and syncing but I am still running into this issue. No changes

**Comment by abzcoding** [comment]
might be related: https://github.com/nvim-telescope/telescope.nvim/issues/2501

**Comment by soerenmartius** [comment]
Awesome thank you! https://github.com/nvim-telescope/telescope.nvim/issues/2501#issuecomment-1541226467 solved it for me
