### ISSUE TITLE
How to integrate blade_formatter?

### ISSUE THREAD

**Issue by ziriuz84** [abzcoding/lvim#133]
Hi all,
I'm starting to work with Laravel and Blade template engine. I installed via Mason Blade-formatter, but I don't understand how to configure it. I added the following line in lvim/lua/user/null-ls/init.lua:     
`nls.builtins.formatting.blade_formatter.with{filetypes={"php", "blade", "blade.php"}},`

When I try to format with <leader>lf it says null-ls timeout (and it create a file near the one I'm formatting, deleted an instant later).
If I use `:lua vim.lsp.buf.format()` It formats my file, but without Blade rules.

Thanks for all help

**Comment by abzcoding** [comment]
to integrate blade_formatter add the following:
```lua
    nls.builtins.formatting.blade_formatter {
      filetypes = { "php", "blade", "blade.php" },
    },
```
in here:
https://github.com/abzcoding/lvim/blob/7c14d2d0a1a8be9574ab6c90a6df2102014a2b39/lua/user/null_ls/init.lua#L53-L54

**Comment by ziriuz84** [comment]
It seems to work, not always, with timeout at 50000. Is it a possibility that blade formatter is so slow? I'm on a i7 of 11th with 16 GB RAM and I'm working on a file of only 241 rows

**Comment by abzcoding** [comment]
Sadly I'm not familiar with blade formatter or PHP, so I'm not sure about the performance, but maybe there is some tuning that can be done in its settings

**Comment by abzcoding** [comment]
> I tried also to increment lsp timeout using in my config.lua `vim.lsp.buf.format({ timeout_ms = 10000 })` but it seems to override it in some way, the timeout occurs after a few seconds, maybe 1-2 seconds

hmm, maybe null-ls overrides that
