### ISSUE TITLE
characters removed at beginning of line

### ISSUE THREAD

**Issue by alechp** [abzcoding/lvim#136]
Not quite sure where to begin with this. Seems like it should be a simple error, but
- nothing TS related is throwing
- works fine in vanilla lvim

## Code in bloated lvim 
- Characters missing (fresh install of bloated lvim, no config changes)
> <img width="2672" alt="Screenshot 2023-08-08 at 9 30 53 AM" src="https://github.com/abzcoding/lvim/assets/3058939/e9c3d249-e595-4741-95dd-29272f0bc017">

- When we cat out the file, can see the actual file hasn't been changed
<img width="2672" alt="Screenshot 2023-08-08 at 9 49 16 AM" src="https://github.com/abzcoding/lvim/assets/3058939/7ec721fd-c218-4cfe-bf81-7306f367c614">

## Same code in vanilla lvim
<img width="2672" alt="Screenshot 2023-08-08 at 10 12 51 AM" src="https://github.com/abzcoding/lvim/assets/3058939/4f286504-3688-4407-84af-7b490bba7bc3">

## Additional context

- Getting some local null-ls executable errors in :checkhealth but TS lsp is installed and not throwing
> <img width="1036" alt="Screenshot 2023-08-08 at 9 47 26 AM" src="https://github.com/abzcoding/lvim/assets/3058939/760bb620-9ccd-4f0f-a25b-5317e95542a2">

- Everything is synced on fresh install
<img width="2672" alt="Screenshot 2023-08-08 at 9 46 35 AM" src="https://github.com/abzcoding/lvim/assets/3058939/4874c990-bb7c-4561-9531-db747e986af1">

**Comment by abzcoding** [comment]
might be similar to https://github.com/LunarVim/LunarVim/issues/3109, please remove `indent-blankline` and see if that fixes anything for you, aka

change this line in `config.lua`
```lua
lvim.builtin.indentlines.active = true
```
to 
```lua
lvim.builtin.indentlines.active = false
```
and run `:Lazy clean`

**Comment by abzcoding** [comment]
> One unrelated weird thing I've noticed with current (stashing here but don't think it's necessarily worth opening an issue for since it's non-blocking): The Airline/command runner starts full screen and requires manual interaction for each stage. Eventually drops back in to normal UX. Doesn't block anything though, just noticed this difference while running

yeah,  I might need to fix it upstream instead of here
