### ISSUE TITLE
Hello, how to fix this

### ISSUE THREAD

**Issue by Am91T** [abzcoding/lvim#137]
Error detected while processing function <SNR>54_timer_callback[20]..7[71]..matchup#delim#get_current[1].
.<SNR>67_get_delim_multi[3]..matchup#ts_engine#get_delim[3]..<SNR>64_forward:
line    1:
E5108: Error executing lua ...im-macos/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invali
d node type at position 6 for language lua
stack traceback:
        [C]: in function '_ts_parse_query'
        ...im-macos/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
        ...vim-matchup/lua/treesitter-matchup/third-party/query.lua:55: in function 'get_query'
        ...vim-matchup/lua/treesitter-matchup/third-party/query.lua:142: in function 'prepare_query'
        ...vim-matchup/lua/treesitter-matchup/third-party/query.lua:339: in function 'iter_group_results'

        ...vim-matchup/lua/treesitter-matchup/third-party/query.lua:351: in function 'collect_group_resul
ts'
        ...lazy/opt/vim-matchup/lua/treesitter-matchup/internal.lua:46: in function 'fn'
        ...s/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
        ...lazy/opt/vim-matchup/lua/treesitter-matchup/internal.lua:40: in function 'fn'
        ...azy/opt/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:380: in function 'get_matches'
        ...lazy/opt/vim-matchup/lua/treesitter-matchup/internal.lua:102: in function 'fn'
        ...azy/opt/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:380: in function 'get_active_nodes'
        ...lazy/opt/vim-matchup/lua/treesitter-matchup/internal.lua:221: in function 'get_delim'
        [string "luaeval()"]:1: in main chunk

**Comment by abzcoding** [comment]
Hi, please don't use this repo as is. Incorporate parts of it that you like into your config.


For this specific issue, check the comments here -> https://github.com/andymass/vim-matchup/issues/290
