### ISSUE TITLE
Schemas for kubernetes files for yamlls not loading

### ISSUE THREAD

**Issue by OGrigorios** [abzcoding/lvim#138]
Hello, I took inspiration from you **yaml.lua**  file, to setup the schemastore and custom schemas for kubernetes.
However, If I open a **deployment.yaml**, the schema is not loaded, because **hover_action** does not provide me with a hint.

If I specify this:
 ```
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/deployment.json 
```
at the begining of the file, the schema is properly loaded.

Do you maybe have an idea on how to make your `yaml.lua` work? Does it work for you?

Thanks for the effort.

Kind regards

Grigorios

**Comment by abzcoding** [comment]
it seems to be working fine for me, not sure why 🤔 
<img width="1027" alt="Screenshot 2023-11-07 at 15 54 17" src="https://github.com/abzcoding/lvim/assets/10992695/f13b49c3-452d-408f-8def-837bd4cde3f1">

**Comment by OGrigorios** [comment]
Weird!
I really don't understand why, but after copying and pasting your `yaml.lua` and putting in my changes, from the file that didn't work, it works now. 
I'm lost :)
