### ISSUE TITLE
New dressing version raise an error on nightly

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#139]
The latest update to dress.nvim crashes the code actions here:

https://github.com/abzcoding/lvim/blob/e5aa66ff4f84ec2844f4c755007ef68f5cda5c44/lua/user/dress.lua#L22-L26

I have fixed it on my config by changing this to:

```lua
                codeaction = function(action_tuple)
                    local title = action_tuple.action.title:gsub("\r\n", "\\r\\n")
                    local client = vim.lsp.get_client_by_id(action_tuple.ctx.client_id)
                    return string.format("%s\t[%s]", title:gsub("\n", "\\n"), client.name)
                end,
```

Since I have taken a lot of inspiration from your config, here is a potential fix :D

**Comment by abzcoding** [comment]
Thank you very much mate

**Comment by abzcoding** [comment]
https://github.com/abzcoding/lvim/commit/f5c27e93d2c9f972182f87d4f3ea6d2f94d95384

**Comment by crisidev** [comment]
You are very welcome!
