### ISSUE TITLE
Can you please add support for a translation plug-in?

### ISSUE THREAD

**Issue by aeet** [abzcoding/lvim#140]
The specific usage scenario is as follows. When writing code, files like i18n are often added. I would like to ask if there is a plug-in that can use `shift+v` to select and use `:Translate` to automatically translate the selected text into the configuration language?

**Comment by abzcoding** [comment]
hey man, sadly i don't have such a use case so i won't be adding it to the codebase

but you might wanna checkout one of these:
 - [vim-translator](https://github.com/voldikss/vim-translator)
 - [translate.nvim](https://github.com/uga-rosa/translate.nvim)

**Comment by aeet** [comment]
> hey man, sadly i don't have such a use case so i won't be adding it to the codebase
> 
> but you might wanna checkout one of these:
> 
> * [vim-translator](https://github.com/voldikss/vim-translator)
> * [translate.nvim](https://github.com/uga-rosa/translate.nvim)

Thank you very much for your reply. I will try these two plugins and then try to integrate them~
