### ISSUE TITLE
How come I have to use `<leader>+w` every time to make the theme take effect?

### ISSUE THREAD

**Issue by CrazyCatZhang** [abzcoding/lvim#142]
Before `<leader> + w`
<img width="1792" alt="image" src="https://github.com/abzcoding/lvim/assets/67346540/7d438dc3-3bd4-4e32-8042-c479cea61075">

After `<leader>+w`
<img width="1792" alt="image" src="https://github.com/abzcoding/lvim/assets/67346540/212b4b05-f265-471f-b310-d78a70a127b7">

**Comment by abzcoding** [comment]
not sure tbh, i don't need to use `<leader>w` at all,
bear in mind that i'm using a very customized workflow (tmux+wezterm+...)
i would suggest only picking up the parts you like from the config and not using it as as
<img width="646" alt="Screenshot 2024-02-19 at 17 43 37" src="https://github.com/abzcoding/lvim/assets/10992695/5b1ce886-b062-43ea-ae17-9393d1a55367">

**Comment by abzcoding** [comment]
this is what it looks like on my system
<img width="2559" alt="Screenshot 2024-02-19 at 17 46 10" src="https://github.com/abzcoding/lvim/assets/10992695/b4d2d8db-5209-4ad6-9fff-1e61af7cc91f">

**Comment by CrazyCatZhang** [comment]
<img width="252" alt="image" src="https://github.com/abzcoding/lvim/assets/67346540/7d8df42e-5758-4ee7-9c2e-75cd1b15aac9">
What's this~~

**Comment by abzcoding** [comment]
> <img alt="image" width="252" src="https://private-user-images.githubusercontent.com/67346540/306117702-7d8df42e-5758-4ee7-9c2e-75cd1b15aac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTEyODAsIm5iZiI6MTcwODQxMDk4MCwicGF0aCI6Ii82NzM0NjU0MC8zMDYxMTc3MDItN2Q4ZGY0MmUtNTc1OC00ZWU3LTljMmUtNzVjZDFiMTVhYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA2MzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMTg3MzZiNDg1M2MyMzU2NjE0ZTE4NTBmYmU0ZWNlNDJlMGY3ZmE4MWZiNTEyZGFhMmVmOTA2YjcyYWM4OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dGhWGeeNFyPpwExAsOrIncqangzdur8zoauVtsgDoA"> What's this~~

my custmoized tmux

**Comment by abzcoding** [comment]
> 
> That looks great! do you have dotfiles, bro?

thanks, not yet mate

**Comment by CrazyCatZhang** [comment]
I'm looking forward to it.

**Comment by CrazyCatZhang** [comment]
I've noticed something, whenever I use <leader>+w, it changes the theme from catppuccin-mocha to tokyonight.

**Comment by CrazyCatZhang** [comment]
> I've noticed something, whenever I use +w, it changes the theme from catppuccin-mocha to tokyonight.

solved...

**Comment by abzcoding** [comment]
> > I've noticed something, whenever I use +w, it changes the theme from catppuccin-mocha to tokyonight.
> 
> solved...

if you still have issues with the theme, just disable the timebased theme and set a static one (inside `config.lua`)

so instead of https://github.com/abzcoding/lvim/blob/2e58fa5208e0a16d6546d904678ca3043fba0295/config.lua#L4-L5

do

```lua
lvim.colorscheme = "catppuccin-mocha"
lvim.builtin.time_based_themes = false
```

**Comment by CrazyCatZhang** [comment]
<img width="1787" alt="image" src="https://github.com/abzcoding/lvim/assets/67346540/c3ea357c-3f9b-45c2-9fcd-f8c406ca9742">
How do you set the middle bar to match the background color of the theme?

**Comment by abzcoding** [comment]
> <img alt="image" width="1787" src="https://private-user-images.githubusercontent.com/67346540/306301928-c3ea357c-3f9b-45c2-9fcd-f8c406ca9742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDE3MzIsIm5iZiI6MTcwODQ0MTQzMiwicGF0aCI6Ii82NzM0NjU0MC8zMDYzMDE5MjgtYzNlYTM1N2MtM2Y5Yi00NWMyLTlmY2QtZjhjNDA2Y2E5NzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE1MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5N2NkYmUyNjNmN2U1YWFiODA0MTcyM2Q1ZjQ3MzgzZDliYjk1NmFjNmFiMDA1MjQ4Y2Y1NmYzMjg2NWU5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Syr9EnW_J11ozO3Knf6UTb5EjaB2xz-eBHvhPAQWzFE"> How to set the middle bar to the same background color as the theme?

again i'm using a very customized workflow, this script is ran to change the tmux theme ( that bar)
<img width="725" alt="Screenshot 2024-02-20 at 18 34 30" src="https://github.com/abzcoding/lvim/assets/10992695/f4013836-dd09-44e3-b943-5877f8f4b26f">

**Comment by CrazyCatZhang** [comment]
The bar in the picture is the status bar of Neovim, which is likely configured through lualine.lua

**Comment by CrazyCatZhang** [comment]
> this is what it looks like on my system <img alt="Screenshot 2024-02-19 at 17 46 10" width="2000" src="https://private-user-images.githubusercontent.com/10992695/305978257-b4d2d8db-5209-4ad6-9fff-1e61af7cc91f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDI1MjMsIm5iZiI6MTcwODQ0MjIyMywicGF0aCI6Ii8xMDk5MjY5NS8zMDU5NzgyNTctYjRkMmQ4ZGItNTIwOS00YWQ2LTlmZmYtMWU2MWFmN2NjOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE1MTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMWI2MDZhNWZlYTNhYzc1ZTg3MGNiNjUyM2NlYWRjMzM4ZDY3N2U1NGQ2ODczYjZkNzA2ZjhiZmU0M2U3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZOpFLqoRAd3gDP_7P-dvTJ98R8at9FYALf6Sqsmj7U">

How do I get the tmux status bar and neovim status bar on the same line, like in the picture you showed?

**Comment by abzcoding** [comment]
> The bar in the picture is the status bar of Neovim, which is likely configured through lualine.lua

yes i have set my tmux status bar exactly as my lualine

**Comment by abzcoding** [comment]
1. setting custom colorschemes:

https://github.com/abzcoding/lvim/blob/2e58fa5208e0a16d6546d904678ca3043fba0295/lua/user/theme.lua#L447-L464

2. getting current theme colors inside lualine:

https://github.com/abzcoding/lvim/blob/2e58fa5208e0a16d6546d904678ca3043fba0295/lua/user/lualine.lua#L135-L136

3. setting the background color of the part between left and right inside lualine to `colors.bg`

https://github.com/abzcoding/lvim/blob/2e58fa5208e0a16d6546d904678ca3043fba0295/lua/user/lualine.lua#L406-L407

4. and finally automatically setting `status_bg` in `~/.tmux.conf` (the picture that i sent beforehand)

**Comment by CrazyCatZhang** [comment]
Thank you very much, my friend, but the lualine and tmux status bars are still separate, even though the script successfully updates the tmux background.

**Comment by abzcoding** [comment]
> Thank you very much, my friend, but the lualine and tmux status bars are still separate, even though the script successfully updates the tmux background.

You’re welcome, i know they're separate, but i'm setting both of them to the same value to create the illusion that there is no tmux status bar, hence the nice effect in my screenshot

**Comment by abzcoding** [comment]
also i'm using this to show lualine inside tmux status line

https://github.com/vimpostor/vim-tpipeline

**Comment by CrazyCatZhang** [comment]
Thank you, my friend. Following your advice, the status bar looks fantastic now. You have great taste.

**Comment by abzcoding** [comment]
> your tmux status bar theme is Catppuccin or cutsom?

my wezterm terminal theme syncs with my neovim, also my tmux status bar color changes to be in sync with them
<img width="783" alt="Screenshot 2024-02-21 at 18 50 00" src="https://github.com/abzcoding/lvim/assets/10992695/76281dab-0580-4a01-9ba4-77322a8e90ce">

**Comment by CrazyCatZhang** [comment]
Great~i mean,is the tmux theme using the Catppuccin plugin?
 like this `set -g @plugin 'catppuccin/tmux'`

**Comment by abzcoding** [comment]
> Great~i mean,is the tmux theme using the Catppuccin plugin? like this `set -g @plugin 'catppuccin/tmux'`

no

**Comment by CrazyCatZhang** [comment]
Could you share the part of your tmux configuration where you set up the status bar, my friend? thank you.

**Comment by abzcoding** [comment]
> Could you share the part of your tmux configuration where you set up the status bar, my friend? thank you.

```
set -g status-bg "#1E1E2E"
set -g status-fg "#a9b1d6"
set -g status-right ""
set -g status-left ""
set -g status-justify centre
set -g window-status-current-format "#[fg=magenta]#[fg=black]#[bg=magenta]󱫋 #[bg=brightblack]#[fg=white] #W#[fg=brightblack]#[bg=black]"
set -g window-status-format "#[fg=yellow]#[fg=black]#[bg=yellow]#I #[bg=brightblack]#[fg=white] #W#[fg=brightblack]#[bg=black]"
set -g focus-events on
set -g status-style bg=default
set -g status-left-length 120
set -g status-right-length 90
set -g status-justify absolute-centre
```

**Comment by CrazyCatZhang** [comment]
thanks bro ,the status-fg is atuo change?

**Comment by abzcoding** [comment]
> thanks bro ,the status-fg is atuo change?

no `status-bg`

**Comment by CrazyCatZhang** [comment]
Alright, thanks for your patience, bro.

**Comment by abzcoding** [comment]
> Alright, thanks for your patience, bro.

np mate, good luck on your ricing journey

**Comment by CrazyCatZhang** [comment]
thanks, bro! best of luck to you too.

**Comment by CrazyCatZhang** [comment]
bro, i have some new issue, when i change `noice.lua` views
```
    views = {
      cmdline_popup = {
        position = {
          row = 5,
          col = "50%",
        },
        size = {
          width = 60,
          height = "auto",
        },
      },
      popupmenu = {
        relative = "editor",
        position = {
          row = 8,
          col = "50%",
        },
        size = {
          width = 60,
          height = 10,
        },
        border = {
          style = "rounded",
          padding = { 0, 1 },
        },
        win_options = {
          winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
        },
      },
    },
```
my cmdline has a black border. like this
<img width="677" alt="image" src="https://github.com/abzcoding/lvim/assets/67346540/919f4694-a757-4e9f-bbb5-c6f313ef120d">

**Comment by CrazyCatZhang** [comment]
<img width="610" alt="image" src="https://github.com/abzcoding/lvim/assets/67346540/8c816c20-cb6c-4642-91e7-494ffecd74bf">
this is how I want it to be.

**Comment by abzcoding** [comment]
> bro, i have some new issue, when i change `noice.lua` views
> 
> ```
>     views = {
>       cmdline_popup = {
>         position = {
>           row = 5,
>           col = "50%",
>         },
>         size = {
>           width = 60,
>           height = "auto",
>         },
>       },
>       popupmenu = {
>         relative = "editor",
>         position = {
>           row = 8,
>           col = "50%",
>         },
>         size = {
>           width = 60,
>           height = 10,
>         },
>         border = {
>           style = "rounded",
>           padding = { 0, 1 },
>         },
>         win_options = {
>           winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
>         },
>       },
>     },
> ```
> 
> my cmdline has a black border. like this <img alt="image" width="677" src="https://private-user-images.githubusercontent.com/67346540/306836754-919f4694-a757-4e9f-bbb5-c6f313ef120d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODY5NzUsIm5iZiI6MTcwODU4NjY3NSwicGF0aCI6Ii82NzM0NjU0MC8zMDY4MzY3NTQtOTE5ZjQ2OTQtYTc1Ny00ZTlmLWJiYjUtYzZmMzEzZWYxMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA3MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMmQ2NDU2N2FlZjUwYjQwNDBhN2U1YWYwNDM0YTY5YTFjOWFjMzA1YTA4Mjc3YjM1ZWQ2NzIwNmFiODNjZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3XiosjYM8v4nUujy4j97cXDJciCWJJwctrMMiPLDLnE">

mate i can't be answering all your questions 😅 checkout their own repo

https://github.com/folke/noice.nvim/wiki/Configuration-Recipes#clean-cmdline_popup-1

**Comment by CrazyCatZhang** [comment]
Okay,thanks bro, i solved it~~
