### ISSUE TITLE
Is LunarVim not going to be updated anymore?

### ISSUE THREAD

**Issue by CrazyCatZhang** [abzcoding/lvim#145]
see [#4518](https://github.com/LunarVim/LunarVim/discussions/4518#discussioncomment-8963843)

**Comment by abzcoding** [comment]
no, i'll be migrating soon as well

**Comment by CrazyCatZhang** [comment]
Migrate to Astronvim?

**Comment by abzcoding** [comment]
> Migrate to Astronvim?

no, pure neovim

**Comment by crisidev** [comment]
I looked at AstroVim (my config was based on yours) and I think I prefer to follow your lead and migrate to pure neovim as well and not have to deal with distributions that will end up not maintained anymore.

**Comment by williamgoulois** [comment]
Personnaly I chose [Lazyvim](https://github.com/LazyVim/LazyVim) to have a good balance between proximity to vanilla neovim and maintenance by community

**Comment by crisidev** [comment]
I eventually move to a LazyVim based config as well: https://github.com/crisidev/lazyvim/tree/main

More info https://lmno.lol/crisidev/lunarvim-lazyvim
