### ISSUE TITLE
Disable inlayhints for Typescript

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#15]
Hi @abzcoding ,

Thanks for providing this great and comprehensive configuration for LunarVim! When I try to open a `.ts` file, I get an exception:

```
Vim:method typescript/inlayHints is not supported by any of the servers registered for the current buffer
```

How am I supposed to deactivate inlayHints for a specific language server? Thank You!

**Comment by abzcoding** [comment]
hello good sir,
can you check if https://github.com/abzcoding/lvim/commit/3a593748f3e2c041a19a076eb3230a2fa83705bd fixes the issue or not?
( you might need to do a `:PackerSync` and or `:LvimCacheReset`)

**Comment by soerenmartius** [comment]
Hi @abzcoding,

Thank you! That fixed the issue!
