### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#16]
Hey @abzcoding 

It seems that in my setup some icons are missing. The link to recommended fonts in the README.md ends up in a nirvana :) Could you help me to figure out what I am missing here? I've installed nerdfonts and firacode already.
<img width="304" alt="Screenshot 2022-01-11 at 10 13 14" src="https://user-images.githubusercontent.com/930643/148949809-d0b8178e-8cf7-4789-a4e7-18d5c329afd4.png">

**Comment by abzcoding** [comment]
sure thing :)
there are two set of icons
1. in the normal lunarvim, you can use any of the [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts) that you like, bare in mind that you need to configure your terminal to use those fonts as well

2. in my own setup, i'm using [a fork](https://github.com/Nguyen-Hoang-Nam/nvim-mini-file-icons)
https://github.com/abzcoding/lvim/blob/40c7b65cde011b9b98f6627cec32fdcdca68efea/config.lua#L47-L49

and you can check my [terminal configuration](https://github.com/abzcoding/wezterm/blob/d3f9ef7feb747e73bd8fb3680f73ffc7e3466255/wezterm.lua#L14) to see how i'm using them

**Comment by soerenmartius** [comment]
Hey @abzcoding , thanks for your reply. 
I've installed the missing fonts with:

```
brew tap homebrew/cask-fonts
brew search nerd-font
brew install --cask font-fira-code
brew install --cask font-victor-mono-nerd-font
brew install --cask font-iosevka
brew install --cask font-hack-nerd-font
```
(see the corrected line for installing the iosevka) font but still I am not seeing any icons :/ any idea?

**Comment by abzcoding** [comment]
if you want to use `iosevka`,  you need the nerd font variant
<img width="194" alt="Screen Shot 2022-01-11 at 5 58 59 PM" src="https://user-images.githubusercontent.com/10992695/148961500-76b574d7-b449-486d-95ba-df33dbb850e2.png">

basically only nerd font variants contain the icons/glyphs

**Comment by abzcoding** [comment]
same for the fira-code
<img width="202" alt="Screen Shot 2022-01-11 at 6 00 16 PM" src="https://user-images.githubusercontent.com/10992695/148961689-037c500a-d10e-4bd8-9b2b-721e755c2410.png">

**Comment by abzcoding** [comment]
you can also just download and install the fonts directly, for example [FiraCode Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Retina/complete/Fira%20Code%20Retina%20Nerd%20Font%20Complete.ttf)

**Comment by soerenmartius** [comment]
> ```yaml
> font:
>   normal:
>     family: "FiraCode Nerd Font"
>     style: Retina
>   size: 13
>   offset:
>     x: 0
>     y: 8
>   ligatures: true
> ```

Thank you! Not sure if I understood everything correctly. After installing the font variants and using the above-mentioned config (which loads the font in alacritty correctly) the icons still won't show up :/

**Comment by abzcoding** [comment]
> Thank you! Not sure if I understood everything correctly. After installing the font variants and using the above-mentioned config (which loads the font in alacritty correctly) the icons still won't show up :/
> ```

you can't use the mini-file-icons in alacritty -> so please remove this line from your config
```lu
  lvim.builtin.nvim_web_devicons = { active = false }
```

also, here is my full alacritty config, it might be helpful
```yaml
font:
  normal:
    family: "FiraCode Nerd Font"
    style: Retina
  bold:
    family: "FiraCode Nerd Font"
    style: Retina
  italic:
    family: "Hack Nerd Font"
    style: Italic
  bold_italic:
    family: "Hack Nerd Font"
    style: Italic
  size: 13
  offset:
    x: 0
    y: 8

  ligatures: true
  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true
```
other than that, i might suggest doing a `:LvimCacheReset` as well

**Comment by abzcoding** [comment]
[this](https://www.lunarvim.org/configuration/04-nerd-fonts.html#installing-a-font) might be helpfull as well

**Comment by soerenmartius** [comment]
That worked! Thanks!
