### ISSUE TITLE
linux (ubuntu/debian) equivalent for vale and markdownlint-cli

### ISSUE THREAD

**Issue by kraxli** [abzcoding/lvim#18]
Hi

Thanks for this nice config :-). 

I am wondering if there is an linux (ubuntu/debian) equivalent for `vale` and `markdownlint-cli`?

**Comment by abzcoding** [comment]
Hello,

thank you for your kind words

yes there is

```shell
npm install -g markdownlint-cli
```
and [vale installation](https://docs.errata.ai/vale/install)

**Comment by kraxli** [comment]
Thousand thanks

-------- Original Message --------
