### ISSUE TITLE
Duplicated line

### ISSUE THREAD

**Issue by petar-nikov** [abzcoding/lvim#2]
https://github.com/abzcoding/lvim/blob/b87cbda9c128c4e57b319ee8f78b8f00dc9463d5/config.lua#L34

This line duplicates line 29

https://github.com/abzcoding/lvim/blob/b87cbda9c128c4e57b319ee8f78b8f00dc9463d5/config.lua#L29

**Comment by abzcoding** [comment]
tyvm sir
