### ISSUE TITLE
[Help] which-key doesn't show up when triggering commands starting with ',' (comma) character

### ISSUE THREAD

**Issue by pidgeon777** [abzcoding/lvim#20]
Those are my mappings:

```lua
vim.api.nvim_set_keymap("n", ",a", ":Telescope lsp_dynamic_workspace_symbols<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", ",b", ":Telescope buffers<CR>", {noremap = true, silent = true})
```

I would expect *which-key* to show up when pressing the first `,` (comma) character, but this doesn't happen.

**Comment by abzcoding** [comment]
it is not supposed to show up, because which-key only shows up for keys that start with leader(`space`) keybinding and one or two other keys like `g`
if you want to show them using which key, you might wanna use this syntax
```lua
require("which-key").register {
  [",a"] = { "<CMD>Telescope lsp_dynamic_workspace_symbols<CR>", "show workspace symbols" },
  [",b"] = { "<CMD>Telescope buffers<CR>", "show buffers" },
}
```

**Comment by pidgeon777** [comment]
Thanks.

I was probably using an older version because the mappings I posted above worked in my old config (*which-key* showed itself).
