### ISSUE TITLE
How did you make gitsigns "Stage Hunk" keymap for visual mode

### ISSUE THREAD

**Issue by shth** [abzcoding/lvim#22]
Sorry if this sounds stupid :joy:
but how did you make gitsigns "Stage Hunk" keymap (`<leader>gs`) available in visual mode?

I've searched for `stage`, `gitsigns` and `which-key` but couldn't find anything. I've looked at this [keybinding.lua](https://github.com/abzcoding/lvim/blob/4a87e6076ec52bc4055654dddd28a82352d13ec0/lua/user/keybindings.lua) file but couldn't find anything about this as well.

I've tried using this in my own config.lua
```lua
lvim.builtin.which_key.mappings["g"]["s"] = {
    "<cmd>lua require 'gitsigns'.stage_hunk()<cr>", "Stage Hunk", mode="v"
}
```
this works in visual mode, but unfortunately this makes the keymap in normal mode disappear, and `which-key` doesn't support specifying multiple mode at the moment I think? ([issue](https://github.com/folke/which-key.nvim/issues/56))

Thanks in advance!

**Comment by abzcoding** [comment]
can you try
```lua
  lvim.builtin.which_key.vmappings["g"] = {
    name = "+Git",
    s = { "<cmd>lua require 'gitsigns'.stage_hunk()<cr>", "Stage Hunk" },
  }
```

**Comment by abzcoding** [comment]
notice the use of `vmpaggins` instead of `mappings`

**Comment by shth** [comment]
It works, thanks a lot!
