### ISSUE TITLE
theme problem

### ISSUE THREAD

**Issue by venson** [abzcoding/lvim#24]
After the recent lunarvim and your lvim update, I got the following error messages.
This still happens even with reinstall.

```
Error detected while processing /home/venson/.config/lvim/after/plugin/highlights.vim:
line   39:
E5108: Error executing lua /home/venson/.config/lvim/lua/user/theme.lua:333: attempt to index field 'fancy_teles
cope' (a nil value)
stack traceback:
        /home/venson/.config/lvim/lua/user/theme.lua:333: in function 'telescope_theme'
        [string ":lua"]:1: in main chunk
11:04:27 [WARN ] lvim: "Invalid configuration: vim/_meta.lua:170: E474: Invalid argument" file="init.lua", line=
105
```

I trie to comment out the fancy_telescope part in ~/.config/lvim/lua/user/theme.lua, which solve the error message, but the warn message remains.

**Comment by SamirOmarov** [comment]
I see this is closed but Issue still persist on my end too with clean install. Even after this commit https://github.com/abzcoding/lvim/commit/e898e5a4f8ea2a9e358b644e74152dfa01b5fe47

**Comment by venson** [comment]
Thanks for your quickfix. The error messages are gone as expected. But There is a WARN message, and the theme dont behave right
```
00:28:48 [WARN ] lvim: "Invalid configuration: vim/_meta.lua:170: E474: Invalid argument" file="init.lua", line=105
```

![image](https://user-images.githubusercontent.com/590850/160291292-eecd4979-8f8f-4e99-a9e7-84bbec0369c0.png)

**Comment by abzcoding** [comment]
@venson please do a `:PackerCompile`
and if the error appeared again, please run `:messaages` and screenshot the full error

**Comment by abzcoding** [comment]
btw i've added more commits since then, make sure you are on the latest

**Comment by venson** [comment]
1. I'm on the latest Commit [Fix #25]( https://github.com/abzcoding/lvim/commit/26f27da2e68245f68ead31cb3bc1c0fd0fa28315).
2. finished the `:PackerCompile`
3. `00:28:48 [WARN ] lvim: "Invalid configuration: vim/_meta.lua:170: E474: Invalid argument" file="init.lua", line=105` is all I got from `:messages`
4. I suspect that `~/.local/share/lunarvim/lvim/lua/lvim/config/init.lua` may cause the problem, but I cant figure out. 

```
function M:load(config_path)
  local autocmds = require "lvim.core.autocmds"
  config_path = config_path or self.get_user_config_path()
  local ok, err = pcall(dofile, config_path)
  if not ok then
    if utils.is_file(user_config_file) then
      Log:warn("Invalid configuration: " .. err)
    else
      Log:warn(string.format("Unable to find configuration file [%s]", config_path))
    end
  end
```
Does these code relevant?

**Comment by abzcoding** [comment]
@venson ok do this instead
```vim
:PackerSync
```
and then
```vim
:LvimCachaReset
```
if that didn't help either, please open a new issue

**Comment by abzcoding** [comment]
also check these log files for more info
```
~/.cache/nvim/lsp.log
~/.cache/nvim/lvim.log
~/.cache/nvim/log
```
