### ISSUE TITLE
[Bug] Scroll in Lazygit inside toggleterm window

### ISSUE THREAD

**Issue by williamgoulois** [abzcoding/lvim#25]
Hi !

First thank you for your nice config 🚀 
When i open Lazygit from neovim (toggleterm) when i try to scroll down with `j` the cursor does move only after i release it. This does not happen when i scroll up with `k`.

I do not encounter this bug in regular Lazygit (not inside toggleterm)

Quick video with bug demo

https://user-images.githubusercontent.com/37271970/160286876-d792e20f-9bcc-4f2d-ae5d-bf9d149c1a4e.mov

**Comment by abzcoding** [comment]
hi,
thank you for the kind words,
I've been using arrow keys, so I've not noticed this bug before, 
i'll look into it later tonight

**Comment by abzcoding** [comment]
feel free to reopen it, if the issue persists
