### ISSUE TITLE
Keybinding for closing the current buffer stopped working

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#27]
Hi,

The following keybinding stopped working in my setup: https://github.com/abzcoding/lvim/blob/main/lua/user/keybindings.lua#L115
All other bufferline keybindings still seem to work.

```
NVIM v0.7.0-dev+04d2476d3
Build type: Release
LuaJIT 2.1.0-beta3
Latest Lvim stable
```

**Comment by abzcoding** [comment]
Hi,
note that it is `BufferLinePickClose` which means pick the buffer that you want to close
as in the picture below, you need to hit an extra keybinding after `<space>bc`
in this case, I had two options, `c` or `p`  which I chose `p` for `plugins.lua`

https://user-images.githubusercontent.com/10992695/160610522-c9a6656c-aa43-43d7-842b-72fabd9e62d9.mp4


which part is now working?
it doesn't show the characters, or it doesn't close them after pressing the extra chars

**Comment by venson** [comment]
add key binding to BufferLineKill to close current buffer

**Comment by abzcoding** [comment]
> add key binding to BufferLineKill to close current buffer

i have `<shift-x>` or `X` for that already

**Comment by soerenmartius** [comment]
Right - I am obviously too stupid to read the docs! Thanks for the clarification and sorry for the noise!

**Comment by venson** [comment]
I mean if he want to close current buffer in which key, add the binding to which key.

**Comment by abzcoding** [comment]
> Right - I am obviously too stupid to read the docs! Thanks for the clarification and sorry for the noise!

no worries mate, it happens 😅
