### ISSUE TITLE
LvimInfo error

### ISSUE THREAD

**Issue by ulrikmonrad** [abzcoding/lvim#28]
While trying to isolate why Packer rollbacks to a snapshot,  10 - 20 seconds after using PackerSync, i noticed the follow error when running LvimInfo.

Not sure if its more related to Lunarvim, if so i'll close here and repost.

E5108: Error executing lua vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function <vim/shared.lua:0>
        vim/shared.lua: in function 'tbl_filter'
        ...elliot/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:105: in function 'make_override_info'
        ...elliot/.local/share/lunarvim/lvim/lua/lvim/core/info.lua:153: in function 'toggle_popup'
        [string ":lua"]:1: in main chunk

Seems my primary issue is related to the previous ones posted by Venson.

Using version:
NVIM v0.7.0-dev+1292-ge9b53f3fb
Build type: Release
LuaJIT 2.1.0-beta3

and already pulled your latest commits.

**Comment by abzcoding** [comment]
please do not run `:LvimInfo` in the startup page (dashboard )

only call when you have a buffer open

**Comment by abzcoding** [comment]
feel free to reopen this issue if you are facing it outside of dashboard
