### ISSUE TITLE
jdtls null-ls/lsp error 

### ISSUE THREAD

**Issue by Axklen** [abzcoding/lvim#29]
Having a problem with jdtls. Using archLinux, zsh, neovim nighly, lvim rolling and your config (all up2date). jdt.ls is attached and working but some lsp/null-ls features arent working. CheckHealth is fine. I did `:LspInstall jdtls`. No reference-checks/doc-signatures/auto-imports and so on. However some lsp features are working. 

I get "full" jdtls functionality using [ChristianChiarulli](https://github.com/ChristianChiarulli/nvim) nvim(from scratch) config.

When open a java file i get this lsp error: .../vim/lsp/rpc.lua:420 "rpc" "java" "stderr" "Error: Unable to access jarfile \n"

`:LspInfo`
![image](https://user-images.githubusercontent.com/34007593/161431053-7347fcc6-f2b2-46a0-98e3-5058f8f82bdf.png)

`lsp.log`
![image](https://user-images.githubusercontent.com/34007593/161431138-1d9906db-8776-4e31-a5bd-9586b3d3a961.png)

`lvim -v`
![image](https://user-images.githubusercontent.com/34007593/161431294-e6adc213-2a9c-474b-95fc-0279522a93cc.png)

I dont know how to debug that error further.

**Comment by abzcoding** [comment]
tbh I've not done java programming since college, so 😅 

but let me look into it

**Comment by Axklen** [comment]
ty, i can provide more info if needed

**Comment by Axklen** [comment]
`:LspInfo` from Chris nvim cfg
![image](https://user-images.githubusercontent.com/34007593/161432366-c5a02118-ce42-4ae1-9ee6-7dd94fedd077.png)
seems like null-ls not attaching correcly

**Comment by Axklen** [comment]
not sure if its related or makes sense but seems strange that the paths are missing:
![image](https://user-images.githubusercontent.com/34007593/161433017-0d853cc1-f8de-4d69-97c4-c9f4286db80e.png)

**Comment by abzcoding** [comment]
@Axklen can you check the latest commit?

just make sure to run the following (for java debugging and testing support)
```shell
git clone git@github.com:microsoft/java-debug.git ~/.config/lvim/.java-debug
cd ~/.config/lvim/.java-debug/
./mvnw clean install
git clone git@github.com:microsoft/vscode-java-test.git ~/.config/lvim/.vscode-java-test
cd ~/.config/lvim/vscode-java-test
npm install
npm run build-plugin
```

**Comment by Axklen** [comment]
im on it, just need to install javaSE-11 XD

**Comment by abzcoding** [comment]
> im on it, just need to install javaSE-11 XD

why?

**Comment by Axklen** [comment]
somehow `./mvnw clean install` throwed an ERR. constraints for JavaSE-11 failed. Installed 11 and passed the mvnw install.
Did all your commands succesfully. pulled the last commit. no jdt.ls isnt attaching anymore XD.
Ill try reinstalling the LSP with LvimChacheReset

**Comment by abzcoding** [comment]
> somehow `./mvnw clean install` throwed an ERR. constraints for JavaSE-11 failed. Installed 11 and passed the mvnw install.
> Did all your commands succesfully. pulled the last commit. now jdt.ls isnt attaching anymore XD.
> Ill try reinstalling the LSP with LvimChacheReset

w8 a bit , let me test it locally

**Comment by abzcoding** [comment]
it should be fixed now, btw it works with java 13 as well, i can test higher versions too

**Comment by abzcoding** [comment]
yeah it works with java 18 as well

**Comment by abzcoding** [comment]
just make sure that you are using this commit https://github.com/abzcoding/lvim/commit/c0416c056efc7257e2bb5864d3bff31f626cc9e8

cause i did a force push

**Comment by abzcoding** [comment]
ok did a bit of cleanup and also enabled java formatting 😅 
so maybe use https://github.com/abzcoding/lvim/commit/6d9cd80e1d17ae66f30aac2640666c1ff1a74f01

**Comment by Axklen** [comment]
hmm, not sure why but my jdt.ls isnt attaching anymore and im getting the same lsp.log error with jar not found. Im on you latest "fix #29" commit :/
ill try to debug my issue more.. maybe i do a cleaninstall of lvim with your newest commits

**Comment by abzcoding** [comment]
yeah do a reinstall and if that didn't help
change this line
```lua
vim.lsp.set_log_level "warn"
```
into
```lua
vim.lsp.set_log_level "info"
```

and check `~/.cache/nvim/lsp.log`
also i'm on mac so maybe try checking this part if you are getting `jar not found`

**Comment by abzcoding** [comment]
```lua
local home = os.getenv "HOME"
local launcher_path = vim.fn.glob(
  home .. "/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"
)
if vim.fn.has "mac" == 1 then
  WORKSPACE_PATH = home .. "/workspace/"
  CONFIG = "mac"
  launcher_path = vim.fn.glob(
    home .. "/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_*.jar",
    1,
    1
  )[1]
elseif vim.fn.has "unix" == 1 then
  WORKSPACE_PATH = home .. "/workspace/"
  CONFIG = "linux"
else
  print "Unsupported system"
end
```

**Comment by Axklen** [comment]
ill try that, ty very much. can report back if was able to fix that annoying bs ;)

**Comment by abzcoding** [comment]
> ill try that, ty very much. can report back if was able to fix that annoying bs ;)

yeah hopefully you can get it fixed, this is what mine looks like rn:
<img width="1340" alt="Screen Shot 2022-04-03 at 8 43 43 PM" src="https://user-images.githubusercontent.com/10992695/161437348-041cb9eb-4827-451e-ba03-fecd7e5f6c13.png">

**Comment by Axklen** [comment]
strange thing is its running in nvim on the same machine. i get this in lsp.log with info:
[INFO][2022-04-03 18:14:03] .../vim/lsp/rpc.lua:261	"Starting RPC client"	{  args = { "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product=org.eclipse.jdt.ls.core.product", "-Dlog.protocol=true", "-Dlog.level=ALL", "-javaagent:/home/axklen/.local/share/nvim/lsp_servers/jdtls/lombok.jar", "-Xms1g", "--add-modules=ALL-SYSTEM", "--add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-jar", "", "-configuration", "/home/axklen/.local/share/nvim/lsp_servers/jdtls/config_linux", "-data", "/home/axklen/workspace/axklen" },  cmd = "java",  extra = {}}

Somehow its not translating "-jar", "" ... ill dig into that

**Comment by abzcoding** [comment]
> strange thing is its running in nvim on the same machine. i get this in lsp.log with info: [INFO][2022-04-03 18:14:03] .../vim/lsp/rpc.lua:261 "Starting RPC client" { args = { "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product=org.eclipse.jdt.ls.core.product", "-Dlog.protocol=true", "-Dlog.level=ALL", "-javaagent:/home/axklen/.local/share/nvim/lsp_servers/jdtls/lombok.jar", "-Xms1g", "--add-modules=ALL-SYSTEM", "--add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-jar", "", "-configuration", "/home/axklen/.local/share/nvim/lsp_servers/jdtls/config_linux", "-data", "/home/axklen/workspace/axklen" }, cmd = "java", extra = {}}
> 
> Somehow its not translating "-jar", "" ... ill dig into that

i had the same issue hence i did this
```lua
local  launcher_path = vim.fn.glob(
    home .. "/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_*.jar",
    1,
    1
  )[1]
```
instead of 
```lua
local launcher_path = vim.fn.glob(
  home .. "/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"
)
```

**Comment by abzcoding** [comment]
https://github.com/abzcoding/lvim/blob/6d9cd80e1d17ae66f30aac2640666c1ff1a74f01/ftplugin/java.lua#L12-L19

**Comment by Axklen** [comment]
how can i debug `vim.fn.has` return value?

**Comment by Axklen** [comment]
its just `local launcher_path = vim.fn.glob(home .. "/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_*.jar")` istn returning anything for me via lvim, but in nvim its working

**Comment by abzcoding** [comment]
> its just `local launcher_path = vim.fn.glob(home .. "/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_*.jar")` istn returning anything for me via lvim, but in nvim its working

yeah i know, and that is why i changed it like up there, let me do another commit and you can test that, w8

**Comment by Axklen** [comment]
jeah, thats it

**Comment by abzcoding** [comment]
ok please check https://github.com/abzcoding/lvim/commit/14dd54298f8a44a87e12851938f197d01c2bc9f2

**Comment by abzcoding** [comment]
i'll be away for an hour or two, test it and let know

**Comment by Axklen** [comment]
jup, works fine. ty very much

**Comment by Axklen** [comment]
btw. love your cfg. have a nice day

**Comment by abzcoding** [comment]
![feels-good-pepe](https://user-images.githubusercontent.com/10992695/161441573-54e3b468-9edd-4b59-82dd-8a49149585dd.gif)

**Comment by Axklen** [comment]
just one last comment for now. i had this issue: `https://github.com/microsoft/java-debug/issues/405` so reverting back to 0.34 did the trick ;) maybe mac got over it XD

**Comment by bernardo-jac** [comment]
two years later, thx @abzcoding
