### ISSUE TITLE
Some issues with async.lua and eslint_d

### ISSUE THREAD

**Issue by Shar51** [abzcoding/lvim#3]
I'm wondering if such a noob-like question is allowed but I really like your config @abzcoding and wondering if you can help me with this error I got.

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed
 with this message: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:152: command eslint_d is not executable (make s
ure it's installed and on your $PATH)
```
I've been looking anywhere to find where the path to the problem at, but can't figure out exactly where.
Thanks

**Comment by abzcoding** [comment]
sure, that means you are trying to use `eslint_d` but that is not available in your system
so you need to install it
```sh
npm install -g eslint_d
```

**Comment by abzcoding** [comment]
btw hop on discord if you had any questions, i'm usually available and willing to answer 😅

**Comment by Shar51** [comment]
> btw hop on discord if you had any questions, i'm usually available and willing to answer

Cool, will jump into it now.
Thank you for the solution.

**Comment by abzcoding** [comment]
> > btw hop on discord if you had any questions, i'm usually available and willing to answer
> 
> Cool, will jump into it now.
> Thank you for the solution.

the address to our discord -> https://github.com/LunarVim/LunarVim#resources
in the #lunarvim channel

**Comment by Shar51** [comment]
> > > btw hop on discord if you had any questions, i'm usually available and willing to answer
> > 
> > 
> > Cool, will jump into it now.
> > Thank you for the solution.
> 
> the address to our discord -> https://github.com/LunarVim/LunarVim#resources
> in the #lunarvim channel

already in it :smile: 
You guys are awesome, love the server.
