### ISSUE TITLE
Ftplugin configurations won't work

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#30]
After upgrading to the latest version, it seems that configurations in `./after/ftplugin` aren't working anymore.
For example, I have a file `./after/ftplugin/yaml.vim` with the following content:

```
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
```

But it doesn't seem to be recognized. In a `.yaml` or `.yml` file, tabs won't get expanded unless I explicitly set `:set expandtab`

**Comment by abzcoding** [comment]
can you check if this works?
```lua
lvim.autocommands.custom_groups = {
    { "Filetype", "yaml", "setlocal expandtab ts=2 sw=2" },
}
```

**Comment by abzcoding** [comment]
>  it seems that configurations in ./after/ftplugin aren't working anymore.

they do work, you can try opening a python file or a go file, and LSP would start ( which means those are working)
but `tabstop`,`shiftwidth` and `expandtab` and other similar settings work a bit different so they might be overridden somewhere else

**Comment by abzcoding** [comment]
<img width="1345" alt="Screen Shot 2022-04-04 at 3 22 41 PM" src="https://user-images.githubusercontent.com/10992695/161529332-4144eb57-3603-4701-bc40-00b3038a4a45.png">

btw can you open a yaml file and run `:set shiftwidth?` or `:set expandtab?`
because they work just fine for me

**Comment by soerenmartius** [comment]
Hm, it's pretty weird. All options seem to work but `expandtab`. It works once I run `:set expandtab` in a buffer but not through the ftplugin configuration

**Comment by soerenmartius** [comment]
Ok found it - the issue was a conflict with the editorconfig. `verbose set expandtab?` helped me debugging
