### ISSUE TITLE
persistence error

### ISSUE THREAD

**Issue by JoeGu08** [abzcoding/lvim#31]
# I can't use persistence when I quit
what's wrong with it 
    
```
E5108: Error executing lua ...ack/packer/opt/persistence.nvim/lua/persistence/init.lua:39: Vim(autocmd):E216: No such group or event:
Persistence
stack traceback:
        [C]: in function 'cmd'
        ...ack/packer/opt/persistence.nvim/lua/persistence/init.lua:39: in function 'stop'
        [string ":lua"]:1: in main chunk
```

**Comment by abzcoding** [comment]
the only time that i use `persistence.nvim` is by hitting `s` in the dashboard menu, and that works fine

i'm not sure what is your issue, but you can try removing the `lazyloading` part, 
remove these lines, reopen and run `:PackerCompile` 
https://github.com/abzcoding/lvim/blob/38d662584f92730908ffcb5bf4057db79639a6eb/lua/user/plugins.lua#L219-L220

see if that helps with anything

**Comment by JoeGu08** [comment]
thank you,it seems fine now🙏
