### ISSUE TITLE
pcre2 fails to install with packer.nvim

### ISSUE THREAD

**Issue by ulrikmonrad** [abzcoding/lvim#32]
I've been trying to figure out why pcre2 fails every single time i update with PackerSync. Have you encountered this issue before?

```
✗ Failed to install pcre2
Cloning into 'lua-pcre2'...
Note: switching to 'ae3fdf9155db6981ff9a60339739303c0661dab7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false
Submodule 'deps/lauxhlib' (https://github.com/mah0x211/lauxhlib.git) registered for path 'deps/lauxhlib'
Cloning into '/private/var/folders/p0/ky08kpq12hb7nz12bwk6tlhm0000gp/T/luarocks_pcre2-0.2.0-1-X9kWtb/lua-pcre2/deps/lauxhlib'...
Error: Could not find header file for LIBPCRE2
  No file pcre2.h in /usr/include
  No file pcre2.h in /include
You may have to install LIBPCRE2 in your system and/or pass LIBPCRE2_DIR or LIBPCRE2_INCDIR to the luarocks command.
Example: luarocks install pcre2 LIBPCRE2_DIR=/usr/local

 Press 'q' to quit
 Press '<CR>' to show more info
 Press 'd' to show the diff
 Press 'r' to revert an update
 Press 'R' to retry failed operations
```

**Comment by abzcoding** [comment]
I've never seen this issue before, please run
```shell
rm -rf ~/.config/lvim/plugin
```
and then open lvim and run
```vim
:PackerCompile
```
to make sure that is not the cause

after that, do the following
```shell
xcode-select --install
brew install pcre2
```
hopefully, this fixes your issue

**Comment by ulrikmonrad** [comment]
It didn't. Same issue still appears. Already had pcre2 via brew. Tried following various leads but can't get Packer.nvim to use the lib.

Also when PackerSync finishes it defaults to this
<img width="841" alt="Screenshot 2022-04-09 at 19 34 52" src="https://user-images.githubusercontent.com/80106041/162585128-3224e5a3-f9b7-428a-8c4a-40923e116f35.png">
 theme.
<img width="943" alt="Screenshot 2022-04-09 at 19 33 23" src="https://user-images.githubusercontent.com/80106041/162585093-78ae4b3c-6ed3-4d84-bd11-da387a1e5ebf.png">

**Comment by abzcoding** [comment]
yeah the theme thingy gets fixed if you reopen lvim or or run `:PackerCompile`

but the `lua-pcre2` is very weird, what is the output of this command?
```shell
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
```

**Comment by ulrikmonrad** [comment]
c7f6b386744a8e8e64947c040e054d424c58c0c8

**Comment by abzcoding** [comment]
well, I have no idea why is this happening 😢 

i would suggest removing my config, using a minimal `config.lua`, for example -> https://github.com/LunarVim/LunarVim/blob/rolling/utils/installer/config.example.lua

and run `:PackerSync` there and see if that works or not

**Comment by ulrikmonrad** [comment]
No failed install of PCRE present in PackerSync when i use the minimal config you posted

**Comment by abzcoding** [comment]
yep create a new issue on [packer.nvim](https://github.com/wbthomason/packer.nvim) repo, it has nothing to do with my config :)

**Comment by ulrikmonrad** [comment]
Error fixed itself apparently. No more issues reported when doing PackerSync. Thanks for the help abzconding.
