### ISSUE TITLE
nvim-cmp problem

### ISSUE THREAD

**Issue by JoeGu08** [abzcoding/lvim#33]
Nvim-cmp has changed recently.And it has a problem now.Please fix this🙏🙏🙏

```
[nvim-cmp] documentation is deprecated.
[nvim-cmp] Please use window.documentation= "native" instead.
```

**Comment by abzcoding** [comment]
yep, w8 a bit for this to be merged
https://github.com/LunarVim/LunarVim/pull/2461

**Comment by abzcoding** [comment]
This should be fixed
