### ISSUE TITLE
更新以后报了这个错

### ISSUE THREAD

**Issue by 505384662** [abzcoding/lvim#34]
![image](https://user-images.githubusercontent.com/31720616/163418136-f0d3ddb0-8953-42ee-abdc-f836e68b85cc.png)
更新以后报了这个错

**Comment by abzcoding** [comment]
请运行 `:PackerSync` 和 `:LvimCacheReset` 然后重新打开

**Comment by abzcoding** [comment]
我正在关闭这个问题，如果你仍然面临它，请随时重新打开它
