### ISSUE TITLE
Move from copilot.vim to copilot.lua

### ISSUE THREAD

**Issue by Uzaaft** [abzcoding/lvim#35]
[This](https://github.com/zbirenbaum/copilot.lua) should possibly make config easier to integrate with the existing cmp plugin by using [copilot-cmp](https://github.com/zbirenbaum/copilot-cmp)

**Comment by Uzaaft** [comment]
I can open a PR for this if you're interested in testing this out. I did so on my laptop a couple of weeks ago, and the experience was better IMHO.

**Comment by abzcoding** [comment]
> I can open a PR for this if you're interested in testing this out. I did so on my laptop a couple of weeks ago, and the experience was better IMHO.

that would be wonderful <3

**Comment by Uzaaft** [comment]
Disclaimer:
![image](https://user-images.githubusercontent.com/48220549/163789715-9d165318-0c2d-42db-9ef7-9bade122e1cd.png)

**Comment by pidgeon777** [comment]
In Windows there are two big problems:

- `copilot.vim`: it crashes as soon as two or more buffers are open and insert mode is entered in one of them.
- `copilot.lua`: no autocomplete suggestion is given, even it `copilot` LSP allegedly started.

**Comment by Uzaaft** [comment]
@pidgeon777  You should take that up with the plugin owners. And disable them in your config

**Comment by abzcoding** [comment]
> In Windows there are two big problems:
> 
> * `copilot.vim`: it crashes as soon as two or more buffers are open and insert mode is entered in one of them.
> * `copilot.lua`: no autocomplete suggestion is given, even it `copilot` LSP allegedly started.

yeah sadly i don't use windows at all ( macbook + linux workstation) so I've not tested it on windows, but i would suggest doing what Uzaaft said ( disabling them temporarily and reporting the bug to the plugin owners)

**Comment by pidgeon777** [comment]
I just updated my Neovim to this version (I was using a previous v0.7.0 nighly version):

https://github.com/neovim/neovim/releases/tag/v0.7.0

`copilot.lua` is not working still, but `copilot.vim` at least now doesn't make Neovim crash anymore, fortunately.

Great plugin, though.

**Comment by abzcoding** [comment]
> I just updated my Neovim to this version (I was using a previous v0.7.0 nighly version):
> 
> https://github.com/neovim/neovim/releases/tag/v0.7.0
> 
> `copilot.lua` is not working still, but `copilot.vim` at least now doesn't make Neovim crash anymore, fortunately.
> 
> Great plugin, though.

yeah i'm only using `copilot.vim` as well, and yes it is a wonderful plugin
