### ISSUE TITLE
[Bug] `which-key` module is not correctly loaded in `keybindings.lua`

### ISSUE THREAD

**Issue by pidgeon777** [abzcoding/lvim#38]
If I add this line at the start of `keybindings.lua`:

```lua
local whk_status, whk = pcall(require, "which-key")
if not whk_status then
  print("Error loading which-key: " .. whk_status)
  return
end
```

then the following error is reported, after a `LvimCacheReset` command:

```lua
11:33:40 [WARN ] lvim: "Invalid configuration: ...nfigurations\\Neovim\\config\\lvim/lua/user/keybindings.lua:5: attempt to concatenate local 'whk_status' (a boolean value)" file="init.lua", line=112
```

If I restart Neovim again, everything gets loaded with no warnings (probably cache affected that).

How could the `which-key` module be correctly loaded (through the `pcall`) in `keybindings.lua` after a cache reset?

**Comment by abzcoding** [comment]
that error means you can't concatenate string and boolean which means yeah the `which-key` is not loaded yet
which makes sense because you are removing the entire cache.

to make sure that `which-key` is loaded use this function instead
```lua
lvim.builtin.which_key.on_config_done = function(whk)
  -- add your whk keybindings here
  -- whk.register(stuff)
end
```
that makes sure which_key is loaded

**Comment by pidgeon777** [comment]
Ok, so that function should be inserted just once in the `keybindings.lua` file, and in no other files? For example, `config.lua`, or plugin-specific files. I'm asking because maybe multiple declarations of it could overwrite the other ones?

Also, in `keybindings.lua`, is there a place where you would suggest adding it?

**Comment by abzcoding** [comment]
let me make it a bit less confusing,
it doesn't matter where you put those, or the fact that it doesn't properly load after `:LvimCacheReset`
because we are basically reading the config, and creating a cache of it, so it might act weird when there is no cache available but it will work perfectly fine after the cache has been created, so don't worry about it 😅
