### ISSUE TITLE
null-ls error after pulling the latest changes

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#43]
Hi, 

Thanks again for providing this awesome configuration!

After pulling the latest changes from this repository, I am running into an error in all `*.ts` and `*.vue` files.
<img width="1200" alt="Screenshot 2022-05-12 at 11 46 12" src="https://user-images.githubusercontent.com/930643/168042945-5acf5108-0e09-437c-adcd-09042f171672.png">

Any idea on how to resolve this?

**Comment by abzcoding** [comment]
the issue comes from this plugin ->
https://github.com/kosayoda/nvim-lightbulb/blob/407f05c71f757f09f775229d5709a3592f1a6910/lua/nvim-lightbulb/init.lua#L210

**Comment by abzcoding** [comment]
> Gotcha - what's the recommended approach? Is this an issue with the actual plugin?

yeah this is an issue with the plugin,
i have my own way of showing available codelens/codeaction
you can enable it by changing this username from `abz` to your own
https://github.com/abzcoding/lvim/blob/2890caa48e34d06c672c30a2eddff5c1c7a3aa6f/lua/user/autocommands.lua#L109-L110

it looks like this when `code_action` is available
<img width="379" alt="Screen Shot 2022-05-12 at 3 05 10 PM" src="https://user-images.githubusercontent.com/10992695/168052025-dad2dd51-f5cc-4422-a7eb-a38839eb447d.png">
<img width="247" alt="Screen Shot 2022-05-12 at 3 05 17 PM" src="https://user-images.githubusercontent.com/10992695/168052036-ccab4aad-9d2e-4238-8948-de3f7853e81a.png">

and will change to this, when `codelens_action` is available
<img width="428" alt="Screen Shot 2022-05-12 at 3 05 55 PM" src="https://user-images.githubusercontent.com/10992695/168052198-add3b2e4-fa89-4297-8d98-b88db10cb373.png">

**Comment by soerenmartius** [comment]
cool thanks for sharing!
