### ISSUE TITLE
null-ts with typescript and vue files

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#47]
Hey,

After updating to the latest version I am again facing issues with null-ls for `*.ts` and `*.vue` files. Do you have any idea how to resolve this?

Language servers I am using:
- volar
- tsserver
<img width="1233" alt="Screenshot 2022-05-19 at 10 49 05" src="https://user-images.githubusercontent.com/930643/169254175-fbbfb90b-f331-48f6-8712-fb0550099b61.png">
<img width="1494" alt="Screenshot 2022-05-19 at 10 52 37" src="https://user-images.githubusercontent.com/930643/169254180-3bbad925-9346-4932-9864-44834aaffd8e.png">

**Comment by abzcoding** [comment]
can you try updating your neovim version ( yours is from 28 days ago it seems like)

**Comment by soerenmartius** [comment]
> can you try updating your neovim version ( yours is from 28 days ago it seems like)

thanks! upgrading neovim resolved the issue!
