### ISSUE TITLE
warp.dev having problems with whichkey and command history

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#49]
hi,
text behind the whichkey menu is visible. its related to this config. i tested it with lunarvim base config and nvchad and its not happening.. does anyone have a idea what it could be? i disabled some plugins but I didn't find a solution yet
here are some screenshots.
https://github.com/LunarVim/LunarVim/issues/2641

**Comment by abzcoding** [comment]
https://github.com/abzcoding/lvim/blob/449b1bc5144988e02980c57f012da0f825df0a27/lua/user/builtin.lua#L527-L528
comment these lines

**Comment by luxus** [comment]
@abzcoding thanks. yes that helped. is this a missing feature in warp? 


what plugin does this menu?
https://user-images.githubusercontent.com/7449/169513548-2d3d43f2-afd6-48c3-bbb9-adf96eb76984.png

**Comment by abzcoding** [comment]
1. probably ( since it should look like this)
<img width="1448" alt="Screen Shot 2022-05-22 at 4 25 24 PM" src="https://user-images.githubusercontent.com/10992695/169693963-f747864b-d2fa-4bc3-99a3-8e545e47170f.png">

2. `cmp-cmdline` does that
```lua
lvim.builtin.fancy_wild_menu.active = true -- set to false to disable it
```
