### ISSUE TITLE
Ich brauche Hilfe

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#53]
ich habe gesehen du gibst jetzt Unterstützung in allen sprachen.

Nein, es ist nur ein Spass. Danke für die grossartige Arbeit mit deiner Konfiguration

**Comment by abzcoding** [comment]
danke Kumpel <3

**Comment by luxus** [comment]
I hope i didn't step on your nerves and instead I gave you a smile :D

**Comment by abzcoding** [comment]
> I hope i didn't step on your nerves and instead I gave you a smile :D

yes sir you did good 😅

**Comment by soerenmartius** [comment]
Danke auch von meiner Seite :) Grüße aus Berlin!
