### ISSUE TITLE
Null-ls error

### ISSUE THREAD

**Issue by mauriciotp** [abzcoding/lvim#54]
When opening lvim, this error message shows up, any idea on how to solve it?

![image](https://user-images.githubusercontent.com/82242064/172510151-b61480e8-09f9-458e-af29-de61acf15e05.png)

**Comment by luxus** [comment]
what does the rest of the line say? u can see the full line with :nullLsLog
looks like something is not installed

**Comment by mauriciotp** [comment]
When i type :nullLsLog doesn't show anything, but i've got the complete message now
![image](https://user-images.githubusercontent.com/82242064/172516670-1f6aa9b9-404a-440d-b0a8-f7d1a2fcdfba.png)

**Comment by luxus** [comment]
have you fixed it by installing luacheck?

**Comment by mauriciotp** [comment]
Installing luacheck solved the error, thank you so much!

**Comment by abzcoding** [comment]
tyvm @luxus
