### ISSUE TITLE
Persistence error in function 'stop'

### ISSUE THREAD

**Issue by mauriciotp** [abzcoding/lvim#55]
This error below appears when i type the keymappings for persistence, like 'space q d' (quit without saving session). Any idea on how to solve it?

![image](https://user-images.githubusercontent.com/82242064/172513106-85a80620-2059-43c2-b2db-ead8b45600f6.png)

**Comment by luxus** [comment]
Check your neovim version. Are you on the newest nightly version?
try lunarvim rolling
Reset your packer cache, and update lvim.

**Comment by mauriciotp** [comment]
Resetting packer cache doesn't solved the problem :(. I'm currently using neovim 0.7.0 and my lunarvim version is the stable version.

**Comment by luxus** [comment]
install the newest nightly and try lunarvim rolling

**Comment by mauriciotp** [comment]
I've installed lunarvim rolling and newest nightly but the error persists

**Comment by abzcoding** [comment]
That was happening because `<leader>qd` was not quitting the program. It would just remove an augroup
so you might've hit it twice and got the error the second time since that particular augroup has already been removed
