### ISSUE TITLE
NvimTree errors out with new renderer options

### ISSUE THREAD

**Issue by crisidev** [abzcoding/lvim#56]
First of all, thanks for this repo, it is a great source of inspiration for my own neovim setup!

After https://github.com/abzcoding/lvim/commit/cf0a5dfa01d84b754cb8bc09b9a4cd69a3ad54a2, NvimTree is erroring out when starting vim with

```
unknown option: respect_buf_cwd | unknown option: renderer.highlight_git | unknown option: renderer.icons.show | unknown option: renderer.icons.glyphs | unknown option: renderer.root_folder_modifier
```

Disclaimer: I am not using this repo directly, but I am using it as an inspiration, so it could be probably my fault, but I am out of idea. 

I have checked Lvim and the options are defined: https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/nvimtree.lua#L67

I have already reset the cache, it did not help. 

Do you have any idea?

**Comment by abzcoding** [comment]
make sure that you have the latest version of `nvim-tree.lua`

```shell
cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua
git reset --hard
git pull origin master
```

**Comment by crisidev** [comment]
Thanks! It did the trick. I am wondering why a `:LvimSyncCorePlugins` did not do the job.. Anyway, thanks a lot.

**Comment by abzcoding** [comment]
> Thanks! It did the trick. I am wondering why a `:LvimSyncCorePlugins` did not do the job.. Anyway, thanks a lot.

if the plugin developer force pushes and removes the commit that you were on
sometimes packer gets confused
and you won't get the latest changes

I have a weird fix for those occasions
```shell
cd ~/.local/share/lunarvim/site/pack/packer/
find . -type d -depth 2 -exec git --git-dir={}/.git --work-tree=$PWD/{} pull \;
```
