### ISSUE TITLE
Treesitter with incline/in winbar

### ISSUE THREAD

**Issue by Suyashtnt** [abzcoding/lvim#58]
It would be cool to see treesitter in the winbar, E.g you could get the where you are in the document via treesitter

**Comment by abzcoding** [comment]
Hmm, that sounds like a good idea. I'll work on it in a couple of days

**Comment by abzcoding** [comment]
change this line 
https://github.com/abzcoding/lvim/blob/4e862d6412b37be06eac761c37b23afd539c5d95/config.lua#L40-L41
to
```lua
lvim.builtin.winbar_provider = "treesitter" 
```
