### ISSUE TITLE
Html snippets issue

### ISSUE THREAD

**Issue by mauriciotp** [abzcoding/lvim#60]
Recently i was editing a html file, and trying to use html snippets, but, i've got some issues using them. When typing for example h1 and just after, pressing enter, works fine, but, when i type h2 inside h1 and then press enter, this issue occurs:
 
![image](https://user-images.githubusercontent.com/82242064/173419808-8d130f21-c551-4067-b623-330474c0b0a0.png)

![image](https://user-images.githubusercontent.com/82242064/173419979-96ab5539-5a96-4ed4-a59d-2ea18a821c46.png)

I don't know if this is a snippets plugin problem, or a configuration file problem.

**Comment by abzcoding** [comment]
I can confirm that this issue exists, but not sure how to solve it yet 😅

**Comment by rebuilt** [comment]
I use Emmet for any html work.   I haven't had problems with it

**Comment by abzcoding** [comment]
this has been fixed in the latest lunarvim+my lvim
