### ISSUE TITLE
adding themeOption and making timebasedThemes as fallback

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#62]
hi abz,
I tried to add a if statement for the themes, I struggle with understanding the Lua code ;D
can we have a `lvim.builtin.timebasedTheme = true`
it would be a good solution for https://github.com/abzcoding/lvim/issues/59
I like the timebased themes but sometimes I work outside and I need a bright theme

**Comment by abzcoding** [comment]
That sounds like a good idea!

but what should happen if `lvim.builtin.timebasedTheme=false`?

**Comment by luxus** [comment]
okay maybe something 
like `lvim.builtin.themeOption = timeBased` or `themeName` (eg. capuchin) would be even better

**Comment by abzcoding** [comment]
ok that might take a bit
but right now
you can do

```lua
lvim.colorscheme = "catppuccin"
lvim.builtin.time_based_themes = false
-- and install and configure catppuccin
```

**Comment by punkucheung** [comment]
hi abz, please how to solve this problem?  Client 1 quit with exit code 13 and signal 0

**Comment by abzcoding** [comment]
> hi abz, please how to solve this problem? Client 1 quit with exit code 13 and signal 0

Hello mate,
Can you elaborate?

What is the filetype? 
What does the ` ~/.cache/nvim/lsp.log` file show?

**Comment by punkucheung** [comment]
Thank you for your reply。

The first problem is the error in typing "lvim"

Error executing vim.schedule lua callback: Vim:E475: Invalid value for argument cmd: '/home/punku/.local/share/lunarvim/site/pack/packer/start/cmp-tabnine/binaries/4.4.40
/x86_64-unknown-linux-musl/TabNine' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...pack/packer/start/cmp-tabnine/lua/cmp_tabnine/source.lua:236: in function '_on_exit'
        ...pack/packer/start/cmp-tabnine/lua/cmp_tabnine/source.lua:137: in function 'new'
        ...e/pack/packer/start/cmp-tabnine/lua/cmp_tabnine/init.lua:8: in function <...e/pack/packer/start/cmp-tabnine/lua/cmp_tabnine/init.lua:7


The second problem is that there is no response when opening the ".Java" file, and "client 1 quit with exit code 13 and signal 0" is received

**Comment by abzcoding** [comment]
@punkucheung 

for the first problem

```shell
cd ~/.local/share/lunarvim/site/pack/packer/opt/cmp-tabnine
bash ./install.sh
```


for the second problem, refer to [nvim-jdtls docs](https://github.com/mfussenegger/nvim-jdtls#the-client-exits-with-an-error--eclipsejdtls-stopped-working)

or search for `client 1 quit with exit code 13 and signal 0` in google
it is a pretty common issue with java and neovim ( which I don't face)
