### ISSUE TITLE
use the right formatter

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#63]
Hello Sir, 

I am facing some troubles with formatters. Eg, I am working in a typescript project that has an eslint configuration in `.eslintrc`. However, when I am formatting the file, it seems that the language servier (tsserver in my case) will be used for formatting which applies different formatting rules compared when to running `eslint --fix` manually - the later takes the correct configuration.

Do you have any advice on how to fix this behavior?

<img width="329" alt="Screenshot 2022-06-17 at 01 36 29" src="https://user-images.githubusercontent.com/930643/174195464-65086ea4-d1f1-468b-9744-f64d67653324.png">

**Comment by soerenmartius** [comment]
Ok, this seems to be a specific problem with the latest version of the `tsserver` ls - sorry for the noise

**Comment by soerenmartius** [comment]
The problem here was a conflict of formatters. Per default, `tsserver` uses its own formatting capabilities. If you wanna use `tsserver` as your LSP and `eslint` as your formatter, you will need to disable formatting for `tsserver`.

```
client.server_capabilities.documentFormattingProvider = false
client.server_capabilities.documentRangeFormattingProvider = false
```

eg

```
local function on_attach(client, bufnr)
  client.server_capabilities.documentFormattingProvider = false
  client.server_capabilities.documentRangeFormattingProvider = false
  require("lvim.lsp").common_on_attach(client, bufnr)
  api.nvim_buf_create_user_command(bufnr, "CssToJs", css_to_js, { range = true })
  M.buf_map(bufnr, "n", "gs", ":TypescriptRemoveUnused<CR>")
  M.buf_map(bufnr, "n", "gS", ":TypescriptOrganizeImports<CR>")
  M.buf_map(bufnr, "n", "go", ":TypescriptAddMissingImports<CR>")
  M.buf_map(bufnr, "n", "gA", ":TypescriptFixAll<CR>")
  M.buf_map(bufnr, "n", "gI", ":TypescriptRenameFile<CR>")
  M.buf_map(bufnr, "i", "${", change_template_string_quotes, { nowait = true })
  api.nvim_buf_create_user_command(bufnr, "CssToJs", css_to_js, { range = true })
  M.buf_map(bufnr, "n", "gx", ":set opfunc=v:lua.css_to_js<CR>g@")
  M.buf_map(bufnr, "n", "gxx", ":CssToJs<CR>")
  M.buf_map(bufnr, "v", "gx", ":CssToJs<CR>")
end
```

@abzcoding this might be interesting for you also

**Comment by abzcoding** [comment]
it sure is, thanks 👍
