### ISSUE TITLE
Theme Colors are lost after :PackerSync or :LvimUpdate

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#66]
when i use PackerSync i lost all colors and it looks like plain neovim. i always have to restart nvim. is this a normal behaviour ?

**Comment by abzcoding** [comment]
> when i use PackerSync i lost all colors and it looks like plain neovim. i always have to restart nvim. is this a normal behaviour ?

it shouldn't be, but yeah it happens 
sadly don't have time to fix it right now

**Comment by Suyashtnt** [comment]
> when i use PackerSync i lost all colors and it looks like plain neovim. i always have to restart nvim. is this a normal behaviour ?

you can also do leader s c and find the colourscheme you use and it'll fix it
