### ISSUE TITLE
stuck on PackerSync

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#67]
Hi,
Sometimes `PackerSync` stuck while syncing the plugins. I remember that you posted a fix on the lunar vim repo but I didn't find it again
<img width="795" alt="Screenshot 2022-07-02 at 11 10 35" src="https://user-images.githubusercontent.com/7449/176994254-014cbd47-1fc3-4501-8089-7bc83ac766bf.png">

**Comment by abzcoding** [comment]
yeah that issues should be fixed in Lunarvim

can you do a PR there please 😅

```diff
diff --git a/lua/lvim/plugin-loader.lua b/lua/lvim/plugin-loader.lua
index aa275da..184fd5c 100644
--- a/lua/lvim/plugin-loader.lua
+++ b/lua/lvim/plugin-loader.lua
@@ -20,6 +20,7 @@ function plugin_loader.init(opts)
     package_root = opts.package_root or join_paths(vim.fn.stdpath "data", "site", "pack"),
     compile_path = compile_path,
     snapshot_path = snapshot_path,
+    max_jobs = 25,
     log = { level = "warn" },
     git = {
       clone_timeout = 300,
```
