### ISSUE TITLE
testing legendary?

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#68]
can we test this? :D 
https://github.com/mrjones2014/legendary.nvim
looks like it will add all which key commands automatically 

related to https://github.com/LunarVim/LunarVim/issues/2671

**Comment by abzcoding** [comment]
seems like a good idea tbh

**Comment by abzcoding** [comment]
fixed via https://github.com/abzcoding/lvim/commit/f3f8b768883e13bbd56cc37cebfb96502768f875

**Comment by danielo515** [comment]
Have you managed to make the which-key integration to work? Can you explain me how?

**Comment by luxus** [comment]
what you mean @danielo515 
you activate it with space + C and start typing a command. commands that are in which key are searchable

**Comment by danielo515** [comment]
In my configuration I don’t see any of the winch key commands, that’s why I’m asking if it works for you

**Comment by Uzaaft** [comment]
Live grep seems to have been removed from the runnable commands after the introduction of Legendary

**Comment by abzcoding** [comment]
> Live grep seems to have been removed from the runnable commands after the introduction of Legendary

fixed via https://github.com/abzcoding/lvim/commit/a4e6c61fc6d0d0336ba765bb41a5716c07af7e86

**Comment by Uzaaft** [comment]
> > Live grep seems to have been removed from the runnable commands after the introduction of Legendary
> 
> fixed via [a4e6c61](https://github.com/abzcoding/lvim/commit/a4e6c61fc6d0d0336ba765bb41a5716c07af7e86)

MVP 🙌🏾
