### ISSUE TITLE
Issue with new comment api

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#73]
Hi, 

Since https://github.com/abzcoding/lvim/commit/278090c414e0dd267e365fd55eb7fb1a3cf41504, when I am trying to comment code, I am getting the following exception.
<img width="774" alt="Screenshot 2022-08-16 at 08 01 01" src="https://user-images.githubusercontent.com/930643/184808704-6c59eab9-8e44-4c7c-94b5-277c810c032d.png">

- NVIM `v0.8.0-dev+f3c8f3e5d`
- LunarVim `master-47e4e5b`

**Comment by abzcoding** [comment]
yeah, you should probably go back to the commit before that,
I'm using the latest version of plugins 
so you will eventually need to do this change
but lunarvim itself has not yet updated the Comment.nvim plugin

more info: https://github.com/numToStr/Comment.nvim/commit/cd1c38163dd9a11247bcb333d72a36bae76c45f9

**Comment by soerenmartius** [comment]
gotcha! thanks!
