### ISSUE TITLE
Windows intergration

### ISSUE THREAD

**Issue by Masalale** [abzcoding/lvim#78]
How would you go about implementing your Lunarvim config on a Windows machine which is running lvim?

**Comment by luxus** [comment]
follow the normal instructions and replace the nvim folder.
you could run into trouble with all the deps. from this config.
maybe its a better idea to use wsl2. i had success with nixos and https://github.com/viperML/home-manager-wsl (alpine with nix as package manager)

**Comment by abzcoding** [comment]
please follow what luxus said, i have a MacBook and a linux desktop so I don't have any windows machine to try things on
