### ISSUE TITLE
feature: distance.nvim

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#8]
looks like you watched vimconf as well..
have you think about to add https://github.com/chipsenkbeil/distant.nvim ?

https://www.youtube.com/watch?v=BuW2b1Ii0RI

**Comment by abzcoding** [comment]
yes sir, i was actually looking at that plugin, and i wanted to add it in the coming days

**Comment by abzcoding** [comment]
https://github.com/abzcoding/lvim/blob/f87b93eb269a487f217020ce53bc85e2d4299591/config.lua#L32-L32

you can enable and try it, (make sure you do a `:DistantInstall` to install the required libs )

**Comment by luxus** [comment]
nice.. tested and it works :D thanks for adding it.
