### ISSUE TITLE
Can support GO debugging?

### ISSUE THREAD

**Issue by Clz-SkyWalker** [abzcoding/lvim#80]

**Comment by abzcoding** [comment]
1. install `delve`

```shell
go install github.com/go-delve/delve/cmd/dlv@latest
```

2. start the debugging process in lunarvim 
```
<leader>dt -> for setting breakpoints
<leader>dU -> for toggling the debug UI
<leader>ds -> to start the debugging process
```

3. enjoy
<img width="1656" alt="Screen Shot 2022-08-30 at 9 19 13 AM" src="https://user-images.githubusercontent.com/10992695/187351666-4d8d15fc-d09e-419c-a478-1e288d334f28.png">
