### ISSUE TITLE
Enabling copilot breaks command mode tab complete

### ISSUE THREAD

**Issue by fearoffish** [abzcoding/lvim#81]
If I enable copilot, pressing tab in command mode inserts `^I` instead of tab completing. I'm not sure if I missed something, but I'll try and debug it...bear in mind I suck at lua vim though :)

**Comment by abzcoding** [comment]
1. Are you enabling copilot using this?
```lua
lvim.builtin.sell_your_soul_to_devil = { active = true, prada = false }
```

2. can you check if copilot is working or not?
```vim
:Copilot status
```

3. try using the fancy wild menu if nothing else helped
```lua
lvim.builtin.fancy_wild_menu.active = true
```

**Comment by fearoffish** [comment]
1 - yep
2 - yep
3 - This sorted it, so although the problem is probably still there...I'm happy as pie. Thanks very much for being super swift!

**Comment by abzcoding** [comment]
> 1 - yep
> 2 - yep
> 3 - This sorted it, so although the problem is probably still there...I'm happy as pie. Thanks very much for being super swift!

You're welcome, mate
yeah, I should probably dig deeper into that one 🤔 
but I'm a bit busy right now, so I'll add it to my todo list 😅

**Comment by fearoffish** [comment]
I know the feeling...it's our every day, isn't it? 🤣

**Comment by abzcoding** [comment]
> you can change from mode "c" to "s" so that it doesnt touch the command mode at all ( if you are not using fancy_wild_menu or cmp-cmdline)

just comment those two lines to bring back the lunarvim functionality
