### ISSUE TITLE
rust debugging not work 

### ISSUE THREAD

**Issue by robatipoor** [abzcoding/lvim#84]
i was getting error unable find executable file ...
after changing this line in the config rust tools everything was fine for me 
`
  local path = vim.fn.glob(vim.fn.stdpath "data" .. "/mason/packages/codelldb/extension/")
    or vim.fn.expand "~/" .. ".vscode/extensions/vadimcn.vscode-lldb-1.7.4/"

-- change to 

  local path = vim.fn.expand "~/" .. ".vscode/extensions/vadimcn.vscode-lldb-1.7.4/"
`

**Comment by abzcoding** [comment]
run `:Mason` and install `codelldb` 
that would fix the issue
<img width="1680" alt="Screenshot 2022-09-09 at 5 45 41 PM" src="https://user-images.githubusercontent.com/10992695/189358490-0154026a-7e9a-4beb-ab6f-36b14f8dce6a.png">

**Comment by abzcoding** [comment]
@robatipoor this commit should make it a bit more clear for new users -> https://github.com/abzcoding/lvim/commit/0bc4fde98cf5f6f966b60ad4946936b7bc7d4b1a

**Comment by robatipoor** [comment]
thank you

**Comment by luxus** [comment]
haha this config lunarvim has more code then configs for neovim :D 
thanks abzcoding for all your effort :D
