### ISSUE TITLE
scala metals not working

### ISSUE THREAD

**Issue by robatipoor** [abzcoding/lvim#85]
thank you for great repository
i problem with scala sbt project 
after enable metals in config.lua Not only Metals doesn't work for me, Syntax Highlighting also has problems
Can you solve my problem?
i use scala 3 and sbt 1.7 and this is lsp log 
`[START][2022-09-11 20:54:54] LSP logging initiated
[WARN][2022-09-11 20:54:54] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-09-11 20:54:55] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"`

**Comment by abzcoding** [comment]
make sure to fill this with proper version values
 ```lua
 lvim.builtin.metals = {
  active = true
  fallbackScalaVersion = "2.13.7", -- change this
  serverVersion = "0.10.9+271-a8bb69f6-SNAPSHOT", -- and also this
}
```

also [check here](https://github.com/scalameta/nvim-metals#prerequisites) for prerequisites for scala

**Comment by robatipoor** [comment]
I did everything but unfortunately the problem still exists

**Comment by robatipoor** [comment]
thank you
