### ISSUE TITLE
invalid configuration error after update

### ISSUE THREAD

**Issue by robatipoor** [abzcoding/lvim#86]
14:23:27 [WARN ] lvim: "Invalid configuration: /home/username/.config/lvim/config.lua:63: attempt to index field 'lir' (a nil value)" file="init.lua", line=119
14:23:27 [WARN ] lvim: "problems detected while loading plugins' configurations" file="plugin-loader.lua", line=114%

**Comment by abzcoding** [comment]
> 14:23:27 [WARN ] lvim: "Invalid configuration: /home/username/.config/lvim/config.lua:63: attempt to index field 'lir' (a nil value)" file="init.lua", line=119
> 14:23:27 [WARN ] lvim: "problems detected while loading plugins' configurations" file="plugin-loader.lua", line=114%

i'm on the latest lunarvim (rolling branch)
lir has been added theme,
please update your lunarvim installation
or go back to a commit that doesn't have that error
