### ISSUE TITLE
noice from folke

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#87]
can we have it? :D
https://www.reddit.com/r/neovim/comments/xujxos/noicenvim_highly_experimental_plugin_that/

**Comment by abzcoding** [comment]
i mean sure thing ( in a couple of days tho) 😅

**Comment by abzcoding** [comment]
fixed via https://github.com/abzcoding/lvim/commit/4ca82108d18d0ee18010f24a25de77a99f2e6134

btw if you want your cmdline to show up in the middle of the screen
change the following line from `cmdline` to `cmdline_popup`
https://github.com/abzcoding/lvim/blob/4ca82108d18d0ee18010f24a25de77a99f2e6134/lua/user/noice.lua#L10-L11

**Comment by luxus** [comment]
haha @abzcoding you are so quick :D
