### ISSUE TITLE
neo-tree vim keybindings 

### ISSUE THREAD

**Issue by soerenmartius** [abzcoding/lvim#88]
Hi,

It'd be great to have vim keybindings for navigating through the neo-tree filebrowser `hjkl` - those doesn't seem to be working at the moment. 

Thanks!

**Comment by abzcoding** [comment]
hello mate,
i think `j` and `k` are working already ( at least mine works)

what actions should `h` and `l` do ?
maybe `h` like `<BS>` should go updir?
and `l` like `<CR>` should open dir?

**Comment by soerenmartius** [comment]
Hey there,

correct, `j` and `k` are already working to navigate the tree.

> maybe h like <BS> should go updir?
> and l like <CR> should open dir?

Yes - that's what I would suggest :)

**Comment by abzcoding** [comment]
fixed via https://github.com/abzcoding/lvim/commit/aedeed1daaf278703418ddfe0a9e04015866ef52

**Comment by soerenmartius** [comment]
thanks a lot !
