### ISSUE TITLE
only show missing linter errors when opening a file in the linter language.

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#9]
dunno if its related to the config or to lunarvim. I wish lunarvim will start throw errormessages about missing linter like hadolint only when I open a dockerfile and not on start of lunarvim.
I'm playing around with [Lorri](https://github.com/nix-community/lorri)

**Comment by abzcoding** [comment]
sadly this is a lunarvim issue , https://github.com/LunarVim/LunarVim/issues/1833

**Comment by abzcoding** [comment]
@luxus you can use the lazy load method to avoid this issue
https://github.com/abzcoding/lvim/blob/e667902bcf7011e660a73ed989912e20d5eff60d/lua/user/null_ls.lua#L3-L9
