### ISSUE TITLE
(Bug): Colorizer loads after the first buffer is opened

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#90]
Colorizer works only after 1 buffer opened.
steps to reproduce:
`lvim ~/.config/lvim/lua/user/theme.lua`
colorizer is not active (but loaded, i'm able to enable it with `:ColorizerToggle`)
when i open a different file first. And then open a second file with # colors it works

**Comment by abzcoding** [comment]
fixed via https://github.com/abzcoding/lvim/commit/b043ef59fb31f45fc89cb4ecb686fb302a2c0149
