### ISSUE TITLE
enabling navic or treesitter as winbar provider breaks a lot stuff with noice

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#91]
enabling navic or treesitter 
and try some :commands

**Comment by luxus** [comment]
<img width="745" alt="Screenshot 2022-10-12 at 22 57 06" src="https://user-images.githubusercontent.com/7449/195446390-f22bd380-102f-4d68-b376-7944712c3bf2.png">

**Comment by abzcoding** [comment]
it seems like there are some duplicates ( maybe bcz we are using https://github.com/Tastyep/structlog.nvim and multiple sinks)

**Comment by abzcoding** [comment]
also it seems like the only issue is with packer no?

**Comment by abzcoding** [comment]
found the issue, will do a commit here and also a fix in lunarvim

**Comment by abzcoding** [comment]
after https://github.com/LunarVim/LunarVim/pull/3221/files gets merged, i can push my fix and it will be fixed
