### ISSUE TITLE
LSP renaming with instant preview

### ISSUE THREAD

**Issue by luxus** [abzcoding/lvim#92]
https://github.com/smjonas/inc-rename.nvim

**Comment by abzcoding** [comment]
fixed via https://github.com/abzcoding/lvim/commit/d6e2e8618ff8ee793dcacc96cd7548e749f587bd

<img width="1225" alt="Screenshot 2022-10-23 at 9 57 34 AM" src="https://user-images.githubusercontent.com/10992695/197377549-03f9b5b5-5e42-43c7-be80-43a5b9b3dfc3.png">
