### ISSUE TITLE
Telescope live_grep with args

### ISSUE THREAD

**Issue by williamgoulois** [abzcoding/lvim#99]
I need sometimes to search large codebases and lack the ability to filter by filetype and/or location, temporary search inside ignored files...

I found this plugin for Telescope (from the official Telescope org repo) that allows to pass args to `rg` finder
https://github.com/nvim-telescope/telescope-live-grep-args.nvim

For example inside telescope you could type : 
```bash
'state' utils -trust
```
=> this searches the word state inside folder utils only in rust filetypes

Here is a ripgrep guide (for reference args possibilities)
https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md

In second time there is an interesting issue with POCs to be able to search word under cursor, or even search inside the focused directory in nvim-tree.
https://github.com/nvim-telescope/telescope-live-grep-args.nvim/issues/14

Would you be interested in this plugin ?

**Comment by Uzaaft** [comment]
There is already something like this in this config.
`<Leader>+ss` opens up live grep with can be used to search for words based upon file type

**Comment by abzcoding** [comment]
https://github.com/abzcoding/lvim/blob/57b243352e39e6d57a7c7ccb01f63a9ea3cc905f/lua/user/keybindings.lua#L385-L388

**Comment by Uzaaft** [comment]
Turns out that absconding uses that extension. 😂

**Comment by williamgoulois** [comment]
Oh wow that was about to be expected ! I really have to look for all of the features packed in this config 😆
Thanks for this amazing config abz I use it every day since a whole year now 🚀

**Comment by abzcoding** [comment]
You're welcome mate <3
